rootfs.py: minikernel:
fosslinux/live-bootstrap pull request #105
Opened 2021-04-16 17:36 UTC by bittorf

use branch v0.7 from kritis-linux and change settings
to be more i386-alike and add essential kernel feature
'fklock' using latest kernel 3.18.140 from 3.18.x-branch

2021-04-16 19:12 UTC, stikonas commented on rootfs.py
> +                '--arch', 'i386',
Is minikernel going to stay `i386` only? Or would other arches eventually work too? If other arches are planned, maybe instead of hardcoding `i386` we can use args.arch (note that it is `args.arch=x86` and not `i386`, so we might need some map)

2021-04-16 20:02 UTC, bittorf commented on rootfs.py
> +                '--arch', 'i386',
you are right, it support just all archs. the map is internally handled already, but let us focus now on i386

2021-04-20 09:21 UTC, fosslinux requested changes

2021-04-20 09:21 UTC, fosslinux commented on rootfs.py
> +        os.system("test -d kritis-linux && rm -fR kritis-linux")
Please use a python construct.

2021-04-20 09:21 UTC, fosslinux commented on rootfs.py
> +        os.system("git clone --depth 1 --branch v0.7 https://github.com/bittorf/kritis-linux.git")
Use our wrapper function run()

2021-04-20 14:07 UTC, bittorf commented on rootfs.py
> +        os.system("test -d kritis-linux && rm -fR kritis-linux")
ok, done

2021-04-20 14:08 UTC, bittorf commented on rootfs.py
> +        os.system("git clone --depth 1 --branch v0.7 https://github.com/bittorf/kritis-linux.git")
ok, done

2021-04-20 14:09 UTC, stikonas commented on rootfs.py
> +        run('git clone', '--depth 1', '--branch', 'v0.7', 'https://github.com/bittorf/kritis-linux.git')
'git', 'clone'

2021-04-20 16:50 UTC, stikonas commented on rootfs.py
> +        if path.isdir('kritis-linux'):
`os.path`

2021-04-20 17:41 UTC, bittorf commented on rootfs.py
> +        run('git clone', '--depth 1', '--branch', 'v0.7', 'https://github.com/bittorf/kritis-linux.git')
ok, done

2021-04-20 17:42 UTC, bittorf commented on rootfs.py
> +        if path.isdir('kritis-linux'):
ok, done

2021-04-21 19:32 UTC, stikonas approved these changes

2021-04-21 19:33 UTC, merged