Add coreutils 8.32 and fix creation dates
fosslinux/live-bootstrap pull request #115
Opened 2021-05-06 19:59 UTC by melg8

This mr will:
- add build of coreutils 8.32, 
     missing only:
     * `expr`util. (It doesn't appear as executable when installed, so i disabled it for now)
     * regenerated man pages (It needs at least perl 5.8, which is not available for now)
- add single step at the end of bootstrapping which rewrites dates to 1 jan 1970 of files and links, this is first step to achieve fully reproducible resulting file image. 
Now diffoscope shows only relevant differences of builds, and reprorts size reduced from megabytes to 2 digit k-bytes.

I want to thank friendly community in freenode IRC (#bootstrappable) - patiently answering my questions, giving me motivation to contribute to this great project.

Welcoming any suggestions and reviews of my mr.

2021-05-06 20:04 UTC, stikonas requested changes

2021-05-06 20:04 UTC, stikonas commented on sysa.py
> +        self.get_file("https://mirrors.kernel.org/gnu/coreutils/coreutils-8.32.tar.gz")
add end of file newline

2021-05-06 20:04 UTC, stikonas commented on sysa/coreutils-8.32/checksums
> +74a7e140f4be3f1cb2d0e0e77f6786931409f84e0140126298da12f44654540d  /after/libexec/coreutils/libstdbuf.so
same here

2021-05-06 20:04 UTC, stikonas commented on sysa/coreutils-8.32/coreutils-8.32.sh
> +src_prepare() {
More work is needed here to rebuild all pre-generated files.
We don't used pre-generated configure, Makefile.in's etc...
gnulib's Makefile.am is probably auto-generated as well.

2021-05-06 20:07 UTC, bauen1 commented on sysa/coreutils-8.32/checksums
> +74a7e140f4be3f1cb2d0e0e77f6786931409f84e0140126298da12f44654540d  /after/libexec/coreutils/libstdbuf.so
Nit: newline

2021-05-06 20:07 UTC, bauen1 commented on sysa/run2.sh
> +build coreutils-8.32
Would it make sense to push this up further so we have the `touch --date` command available if we want to reduce inconsistencies in a builds source file ?

2021-05-06 20:07 UTC, bauen1 commented on sysa/helpers.sh
> +    find / -exec touch --no-dereference -t 197001010000.00 {} +
I don't really like this hack, as it doesn't really solve the underlying issue (time difference induced differences) but only fixes a symptom.

2021-05-06 20:15 UTC, melg8 commented on sysa/run2.sh
> +build coreutils-8.32
Push further to where? as per https://github.com/coreutils/coreutils/releases - it is last released version?

2021-05-06 20:16 UTC, melg8 commented on sysa.py
> +        self.get_file("https://mirrors.kernel.org/gnu/coreutils/coreutils-8.32.tar.gz")
Fixed in e86f74e5e611d9127b0610ff864134fde5933f91

2021-05-06 20:16 UTC, melg8 commented on sysa/coreutils-8.32/checksums
> +74a7e140f4be3f1cb2d0e0e77f6786931409f84e0140126298da12f44654540d  /after/libexec/coreutils/libstdbuf.so
Fixed in e86f74e5e611d9127b0610ff864134fde5933f91

2021-05-06 20:20 UTC, stikonas commented on sysa/run2.sh
> +build coreutils-8.32
We probably need fairly new automake for this, so we can't push it much further up.

2021-05-06 20:21 UTC, bauen1 commented on sysa/run2.sh
> +build coreutils-8.32
I meant if it would make sense to build it sooner, i don't think coreutils depends on mpc / gmp  ?

2021-05-06 20:45 UTC, stikonas commented on sysa/run2.sh
> +build coreutils-8.32
Yeah, we can push it up a little bit. mpc/gmp will only be needed for newer GCC versions (and I think guile too). But it has to be after automake 1.15.

2021-05-06 20:46 UTC, stikonas commented on sysa/helpers.sh
> +    find / -exec touch --no-dereference -t 197001010000.00 {} +
I guess it depends on how live-bootstrap might be consumed by downstream projects. Which I guess we don't really know at the moment.

2021-05-06 20:53 UTC, melg8 commented on sysa/helpers.sh
> +    find / -exec touch --no-dereference -t 197001010000.00 {} +
I think we should differentiate between two problems:
1. One is "time difference induced differences" - like reported [1](https://github.com/fosslinux/live-bootstrap/issues/102), [2](https://github.com/fosslinux/live-bootstrap/issues/103), [3](https://github.com/fosslinux/live-bootstrap/issues/112)  in other words misbehaviour in builds 
2. noise of "changed" timestamps in filesystem
I think - proper solving of 1-st problem is very important. But 2-nd problem gets in the way.
That's why i've tried to fix 2-nd problem with available tools right now, so we can work on clear view of what's happening with 1st one. 
This is why i add this only as final step. So it is not interferes with build behaviour itself, but works as pure function, getting as input filesystem with files having random modification dates and unifies them to file system with single modification date. So forsing that "moving target" to stop.

From what i learned it's common in community to fix timestamps of dates by using fixed date at the end of creation process:
- in [nixos](https://github.com/NixOS/nix/blob/7c90552879da4d1df99b50c85e94201981e60123/src/libstore/local-store.cc#L457)
- in [debian](https://packages.debian.org/sid/strip-nondeterminism)
- i could find guix example if needed as well. 

I see this as a temporary solution, until much later we will have some more sofisticated filesystem/libc/kernel based sollution. But that solution will do same thing, replacing "real" modification date with "fake" one. 
Pros of that sollution will give us a chanse to have (after we fix non-reproducible behaviour from 1.) a chanse to check whole final filesystem hash sum individually and in CI. And this will add more benefits in development - detecting changes in file system after some tweaks of build scripts, which should not change output, for example. Because now project is missing such viable feedback, by checking only fixed amount of binaries, and not the whole thing.
So that's why i think it could serve us now, until we develop full solution in future.

I want to clear this out - i want this always be the last step of the build, so it will always only provide this last cleanup look and fill. Second, if you really want, we can have both worlds - i can change this step to be optional and off by default - so people / ci services - which need that step - at least can enable it.

2021-05-07 19:34 UTC, stikonas commented on sysa.py
> +                      "https://git.savannah.gnu.org/cgit/gnulib.git/snapshot/gnulib-d279bc.tar.gz"])
minor nitpick: align both URLs (so add one more white space on the second line)

2021-05-07 19:35 UTC, stikonas commented on sysa/coreutils-8.32/coreutils-8.32.sh
> +    . ../../import-gnulib.sh
This should go after removals, otherwise you'll remove newly imported files (which are now not pre-generated)

2021-05-07 21:49 UTC, fosslinux commented on sysa/helpers.sh
> +    find / -exec touch --no-dereference -t 197001010000.00 {} +
I would prefer to hide this behind a optional flag. Because, this masks a few (but not all) underlying problems about non reproducible software.

2021-05-07 21:50 UTC, fosslinux commented on parts.rst
> +.. SPDX-FileCopyrightText: 2021 Melg Eight <mailto:public.melg8@gmail.com>
Please don't include `mailto:`.

2021-05-08 23:18 UTC, stikonas commented on sysa/coreutils-8.32/coreutils-8.32.sh
> +        --enable-no-install-program=expr \
`expr` and `factor` are dynamically linked. I think we should build them instead of skipping.

I think `./configure CFLAGS="-static"` should help with that.
If not you can use `--without-gmp` which would also result in `expr` and `factor` being statically linked.

2021-05-08 23:18 UTC, stikonas commented on sysa/coreutils-8.32/coreutils-8.32.sh
> +     make install PREFIX="${PREFIX}" MAKEINFO="true" DESTDIR="/after/my_test"
Don't forget to fix `DESTDIR` before pushing. I assume this is test code which might be useful for you, but before PR is ready, this needs to be fixed.

2021-05-08 23:18 UTC, stikonas commented on parts.rst
> +
We should move coreutils description a bit higher up where it is being built.

2021-05-10 09:44 UTC, melg8 commented on parts.rst
> +
Fixed in 7c0eb1cef653d2bc57d6902718402c769e89717f

2021-05-10 10:48 UTC, melg8 commented on sysa.py
> +                      "https://git.savannah.gnu.org/cgit/gnulib.git/snapshot/gnulib-d279bc.tar.gz"])
Fixed in 1d8ac019d6efc776740565073e18e0cf05990d3e

2021-05-10 10:48 UTC, melg8 commented on parts.rst
> +.. SPDX-FileCopyrightText: 2021 Melg Eight <mailto:public.melg8@gmail.com>
Fixed in f4d57e2d3517cf101d5fdfd4ffa1dcda926acf6e

2021-05-10 22:37 UTC, melg8 commented on sysa/run2.sh
> +build coreutils-8.32
Fixed in 2258902e17dc294c46fca337708fe03373db01b6

2021-05-10 22:40 UTC, melg8 commented on sysa/coreutils-8.32/coreutils-8.32.sh
> +    . ../../import-gnulib.sh
Fixed in 14a9ef562f2d0a66bfdc3e2a13c50d0ed320d10e

2021-05-10 22:41 UTC, melg8 commented on sysa/coreutils-8.32/coreutils-8.32.sh
> +src_prepare() {
Fixed in 14a9ef562f2d0a66bfdc3e2a13c50d0ed320d10e

2021-05-10 22:43 UTC, melg8 commented on sysa/coreutils-8.32/coreutils-8.32.sh
> +    default_src_prepare
Fixed in 6a2348539b85d220df25f310f9c561f38f7a634d

2021-05-10 22:44 UTC, melg8 commented on sysa/coreutils-8.32/checksums
> +4a1b1c6646c1e209da5fde57b6dd9e51008b422216673ab811ba747984b0beaf  /after/bin/expand
Fixed in 0bd5d8a2c49c0d9a1fdc639e6b1f1db2bc7c9c60

2021-05-11 01:07 UTC, melg8 commented on sysa/helpers.sh
> +    find / -exec touch --no-dereference -t 197001010000.00 {} +
I've tried to implement such functionality in 33a372e722cf9b3d1e5eca6387563a147e8e8cef, suggestions are welcome.

2021-05-16 02:12 UTC, fosslinux requested changes
Reasonable, i especially like the bootstrap.cfg, very nice implementation :)

You shoudl also squash all commits APART from ' Add config file and force timestamp conditional option '

2021-05-16 02:12 UTC, fosslinux commented on sysa/coreutils-8.32/coreutils-8.32.sh
> +  MODULES=(
indentation

2021-05-16 02:12 UTC, fosslinux commented on sysa/coreutils-8.32/files/buffer-lcm
> +# SPDX-FileCopyrightText: 2005-2020 Free Software Foundation, Inc.
I feel like all of these files are included in the gnulib checkout. I would prefer not to vendor these in live-bootstrap if possible.

2021-05-16 02:12 UTC, fosslinux commented on sysa/coreutils-8.32/files/tempname.c.diff
> +SPDX-FileCopyrightText: 2005-2020 Free Software Foundation, Inc.
Please add a header: what is this patch for and why do we need it? Please give it a descriptive name ending in `.patch`.

2021-05-16 02:12 UTC, fosslinux commented on sysa/coreutils-8.32/files/tempname.diff
> +SPDX-FileCopyrightText: 2005-2020 Free Software Foundation, Inc.
Ditto

2021-05-16 02:12 UTC, fosslinux commented on sysa/coreutils-8.32/files/tempname.h.diff
> +SPDX-FileCopyrightText: 2005-2020 Free Software Foundation, Inc.
This looks like it belongs with the first patch.

2021-05-16 02:12 UTC, fosslinux commented on sysa/run2.sh
> +    echo 'Forcing all files timestamps to be 1970 year.'
How about 0 unix time, because that's really what's happening, not some arbitrary date in 1970

2021-05-16 21:00 UTC, melg8 commented on sysa/coreutils-8.32/files/buffer-lcm
> +# SPDX-FileCopyrightText: 2005-2020 Free Software Foundation, Inc.
I'll try to explain current problem and solution. All this files come from coreutils-8.32 packet and not from gnulib. This files are all can be found in gl subfolder of gnulib with same hash/tag as coreutils-8.32.
Problem: when they ship this coreutils in form of tar.gz they don't include thouse files. Instead, they ship generated results based on this files and call of gnulib-tool. As per  @stikonas [review](https://github.com/fosslinux/live-bootstrap/pull/115#discussion_r627727647) i can't just use those generated results, but should instead regenerate them.
So i missing like 15 o so files needed for regeneration (gnulib-tool explicitly warns that this files missing)
This files represents patches from coreutils to gnulib, which eventually should be incorporated inside gnulib.
Possible sollutions:
1. Download not just tar distributed archive with release but git repo. Drawbacks: it would require new implementation of loading stuff in sysa or usage of submodule and possibly more bugs if something not aligned with current coreutils release.
2. Just use later version of gnulib. Drawbacks: 1. not all of fixes are applied to gnulib repo. 2. later version of gnulib starts to rely on gperf. When i tried to build gperf - i found that it need g++ and not just gcc to be built.
3. Just copy-paste missing files (most of them just make files for h/c pairs and call it a day. Possible drawbacks - yea we redistribute them in repo.
So that's current disposition. So if it absolutely needed to be path 1 or worse path 2 i can rebase my mr to use ready to use stuff, but for now i don't have time and motivation to go along this paths and implement by myself. It took quite some time to figure out what's wrong with packages.

2021-05-16 21:08 UTC, stikonas commented on sysa/coreutils-8.32/files/buffer-lcm
> +# SPDX-FileCopyrightText: 2005-2020 Free Software Foundation, Inc.
Regarding 1. It's not necessary to have new implementation in sysa. We can download git archive of a release tag and everything will work more or less the same as releases. In fact we already do that for `sha-2-61555d.tar.gz`. Whether we want to do that for coreutils or not I don't know... @fosslinux what do you think? I'm a bit reluctant to vendor so many files in our `files/` directory, especially when they can be easily obtained elsewhere. In all other places `files` contain something like `config.h` file or some alternative implementation of some file or function. That's why I'm leaning to switching to git archive of release tag.

2021-05-16 21:11 UTC, melg8 commented on sysa/coreutils-8.32/files/tempname.h.diff
> +SPDX-FileCopyrightText: 2005-2020 Free Software Foundation, Inc.
I've tried to merge this 3 files together, gnulib-tool don't like it:
```
mv: cannot stat `tempname.c.diff': No such file or directory
Subprocess error 256
ABORTING HARD
```

2021-05-16 21:14 UTC, melg8 commented on sysa/coreutils-8.32/files/tempname.c.diff
> +SPDX-FileCopyrightText: 2005-2020 Free Software Foundation, Inc.
This is where this files [comes from](https://github.com/coreutils/coreutils/blob/v8.32/gl/lib/tempname.c.diff) what should i write there? i can add comment from git commit which added this file, or just write that this file is part of missing coreutils file hierarchy.

2021-05-16 21:19 UTC, melg8 commented on sysa/coreutils-8.32/files/tempname.diff
> +SPDX-FileCopyrightText: 2005-2020 Free Software Foundation, Inc.
This is where this files [comes from](https://github.com/coreutils/coreutils/blob/v8.32/gl/lib/tempname.h.diff) what should i write there? i can add comment from git commit which added this file, or just write that this file is part of missing coreutils file hierarchy.

2021-05-16 21:30 UTC, stikonas commented on sysa/coreutils-8.32/files/tempname.c.diff
> +SPDX-FileCopyrightText: 2005-2020 Free Software Foundation, Inc.
Yeah, these are not our normal patches (that we put in `patches` dir). If it's upstream `diff` file, we should just ship it without modification.

2021-05-16 21:36 UTC, melg8 commented on sysa/coreutils-8.32/files/buffer-lcm
> +# SPDX-FileCopyrightText: 2005-2020 Free Software Foundation, Inc.
Maybe i found one. 5 will be - load this not from kernel.org but from github.

2021-05-16 21:40 UTC, stikonas commented on sysa/coreutils-8.32/files/buffer-lcm
> +# SPDX-FileCopyrightText: 2005-2020 Free Software Foundation, Inc.
That's basically what I was talking about with git archive. Although, maybe git.savannah.gnu.org is better than github for this.

2021-05-18 12:01 UTC, melg8 commented on sysa/coreutils-8.32/files/tempname.c.diff
> +SPDX-FileCopyrightText: 2005-2020 Free Software Foundation, Inc.
This patch was removed as new solution doesn't require it. Fixed.

2021-05-18 12:01 UTC, melg8 commented on sysa/coreutils-8.32/files/tempname.diff
> +SPDX-FileCopyrightText: 2005-2020 Free Software Foundation, Inc.
This patch was removed as new solution doesn't require it. Fixed.

2021-05-18 12:02 UTC, melg8 commented on sysa/coreutils-8.32/files/tempname.h.diff
> +SPDX-FileCopyrightText: 2005-2020 Free Software Foundation, Inc.
This patch was removed as new solution doesn't require it. Fixed.

2021-05-18 12:02 UTC, melg8 commented on sysa/run2.sh
> +    echo 'Forcing all files timestamps to be 1970 year.'
Fixed.

2021-05-18 12:03 UTC, melg8 commented on sysa/coreutils-8.32/files/buffer-lcm
> +# SPDX-FileCopyrightText: 2005-2020 Free Software Foundation, Inc.
Fixed by using git checkout version instead of release archive. But that required additional patching to fix newly discovered dependencies on generated through gperf files.

2021-05-18 12:04 UTC, melg8 commented on sysa/coreutils-8.32/coreutils-8.32.sh
> +  MODULES=(
That was removed because new implementation doesn't require this step. Fixed.

2021-05-18 12:05 UTC, melg8 commented on sysa/helpers.sh
> +    find / -exec touch --no-dereference -t 197001010000.00 {} +
Was implemented optional, disabled by default action, which could be enabled by flag (--force_timestamps) in rootfs.py.

2021-05-18 23:12 UTC, stikonas commented on sysa/helpers.sh
> +# This functions need `touch` with support of --no-dereference
This function needs `touch` that supports --no-dereference

2021-05-18 23:13 UTC, stikonas commented on sysa/coreutils-8.32/patches/system.h.patch
> +generated files. We don't have gperf on this stage so we can't regenerate them.
at this stage

2021-05-18 23:14 UTC, stikonas commented on sysa/coreutils-8.32/patches/printf.c.patch
> +Remove dependency on unicodeio.h. This drops support for output unicode characters.
for outputting

2021-05-18 23:17 UTC, stikonas commented on parts.rst
> +We rebuild latest available coreutils 8.32 which adds needed options to make build
the latest

2021-05-18 23:21 UTC, stikonas commented on parts.rst
> +results reproducible. For example ``touch --no-dereference``.
I would word it a bit differently. @fosslinux what do you think? I think this might mislead the readers a bit because they'll thing that binaries themselves are not reproducible. But it's only timestamp which is just metadata.

2021-05-18 23:26 UTC, stikonas commented on sysa.py
> +        Creates bootstrap.cfg file which would contain options gathered
I don't like console here, you can start bootstrap without console, e.g. using some GUI. Maybe just write a shorter comment like

Creates bootstrap.cfg file which would contain options used to customize bootstrap.

2021-05-18 23:27 UTC, stikonas commented on sysa/coreutils-8.32/coreutils-8.32.sh
> +# Removing pre-generated files from source code, we will re-generate them.
# Remove pre-generated files from source code

(we are not renegerating info or gmo files as we don't have texinfo or gettext yet)

2021-05-18 23:29 UTC, stikonas commented on sysa/coreutils-8.32/coreutils-8.32.sh
> +remove_generated_configs() {
Rename this function. It's not clear what `configs` are. Maybe `files` instead of `configs`.

2021-05-18 23:29 UTC, stikonas commented on sysa/coreutils-8.32/coreutils-8.32.sh
> +regenerate_configs() {
same here. Rename.

2021-05-18 23:29 UTC, stikonas commented on sysa/coreutils-8.32/coreutils-8.32.sh
> +    touch ./ChangeLog
```suggestion
    touch ChangeLog
```

2021-05-18 23:31 UTC, stikonas commented on sysa/coreutils-8.32/coreutils-8.32.sh
> +    FORCE_UNSAFE_CONFIGURE=1 ./configure CFLAGS="-static -O2" \
why `-O2`? We don't specify it anywhere else and I think it's the default anyway.

2021-05-18 23:32 UTC, stikonas commented on sysa/coreutils-8.32/patches/Makefile.am.patch
> +Remove dependency on po folder. Because we lack sufficient elements
Remove dependency on po folder because we don't have gettext yet.

2021-05-18 23:33 UTC, stikonas commented on sysa/coreutils-8.32/patches/configure.ac.patch
> +Remove dependency on gettext, because we dont have it on this stage
don't have it at this

' is missing and also on->at

2021-05-19 22:52 UTC, stikonas commented on parts.rst
> +build results metadata reproducible. For example, timestamps are changed with
I think it would read better if it says `results of build metadata`.

Also maybe first paragraph is not necessary anymore? We already mentioned that earlier in coreurils 5 text.

2021-05-19 22:55 UTC, stikonas commented on parts.rst
> +build results metadata reproducible. For example, timestamps are changed with
Oh, also maybe rebuild->build. I would reserve "rebuild" for the cases when we rebuild the same version.

2021-05-19 23:06 UTC, stikonas approved these changes
looks good to me.

@fosslinux It would be good if you can re-review too before we merge this (since it's a fairly big MR).

2021-05-23 21:34 UTC, fosslinux approved these changes

2021-05-23 21:34 UTC, merged