New Perl
fosslinux/live-bootstrap pull request #117
Opened 2021-05-16 02:04 UTC by fosslinux

This has taken me a very very long time due to many complexities and interruptions such as exams but we now have the latest perl.

This has a number of random changes and new software, including:

- bison 2.3, backwards bootstraped from 3.4.1, needed to compile perl 5.10
- perl 5.10, used in bootstrap of 5.32.1
- dist, perl's 'Configure' creator
- Newer, less buggy make needed for perl
- Bison 3.4.2 which is built normally and is less buggy needed for perl
- Finally perl 5.32.1, a suprisingly massive jump that happened to work

This adds 10-15 mins to the bootstrap.

2021-05-16 09:26 UTC, stikonas commented on sysa.py
> +                      "https://git.savannah.gnu.org/cgit/gnulib.git/snapshot/gnulib-b28236b.tar.gz"])
all other imports align at quotation mark, so maybe a add a space.

2021-05-16 10:09 UTC, stikonas requested changes

2021-05-16 10:09 UTC, stikonas commented on sysa/bison-3.4.2/bison-3.4.2.sh
> +    default_src_prepare
`default`

2021-05-16 10:09 UTC, stikonas commented on sysa/bison-3.4.2/bison-3.4.2.sh
> +src_prepare() {
remove `.info` files.

2021-05-16 10:09 UTC, stikonas commented on sysa/perl-5.32.1/checksums
> +b9aa5df8e7790d25b610d3568a1fb5ec19d4b7a24ea89032b3e48e6baeff7829  /after/lib/perl5/5.32.1/x86_64-linux/auto/IO/IO.a
That will cause problems on `i386` kernel.

2021-05-16 10:09 UTC, stikonas commented on sysa/perl-5.32.1/perl-5.32.1.sh
> +    default_src_prepare
`default`

2021-05-16 10:09 UTC, stikonas commented on sysa/perl-5.32.1/perl-5.32.1.sh
> +    default_src_install
`default`

2021-05-16 10:09 UTC, stikonas commented on sysa/perl-5.32.1/perl-5.32.1.sh
> +    ./Configure -des -Dprefix="${PREFIX}" -Dcc=gcc -Dusedl=false -Ddate=':' -Dccflags="-U__DATE__ -U__TIME__"
Maybe `-Dtargetarch` will help to keep it 32-bit for now?

2021-05-16 10:10 UTC, stikonas requested changes

2021-05-16 10:10 UTC, stikonas commented on sysa/dist-3.5-236/patches/env.patch
> +SPDX-License-Identifier: Artistic-1.0
This causes `reuse` linter issues.

2021-05-17 20:09 UTC, stikonas commented on SHA256SUMS.sources
> +a3fd3de1f1684f689d823af367ba18bba9fb000d4cef94de60eeb63b1dfe2a6c  dist-3.5-236.tar.gz
Hmm, I'm getting checksum mismatch with this file. Any idea what is going wrong?

2021-05-18 08:29 UTC, fosslinux commented on SHA256SUMS.sources
> +a3fd3de1f1684f689d823af367ba18bba9fb000d4cef94de60eeb63b1dfe2a6c  dist-3.5-236.tar.gz
I am unsure. Perhaps my local version has corruption?

2021-05-18 08:30 UTC, fosslinux commented on sysa/perl-5.10.1/patches/undefined_hack.patch
> +I'm not sure how to appropriately do them, so just patch them.
How do you mean? These were all encountered in the build process.

2021-05-18 08:31 UTC, fosslinux commented on sysa/bison-2.3/bison-2.3.sh
> +    rm src/parse-gram.c src/parse-gram.h
Oops, how did I miss those!

2021-05-18 08:34 UTC, fosslinux commented on SHA256SUMS.sources
> +a3fd3de1f1684f689d823af367ba18bba9fb000d4cef94de60eeb63b1dfe2a6c  dist-3.5-236.tar.gz
I'm pretty sure this case. Please post checksum. New checksum seems to work?

2021-05-18 09:36 UTC, stikonas commented on SHA256SUMS.sources
> +a3fd3de1f1684f689d823af367ba18bba9fb000d4cef94de60eeb63b1dfe2a6c  dist-3.5-236.tar.gz
54437ae4211867de7ad55723f68b94c29cb2f08a23f431e0bbbc9f34ee384f47  dist-3.5-236.tar.gz

2021-05-24 00:09 UTC, fosslinux commented
Updated. I think everything has been addressed. Also fixed make `--build=` option (force i686).

2021-05-24 00:13 UTC, stikonas approved these changes

2021-05-24 00:13 UTC, stikonas commented on sysa/dist-3.5-236/dist-3.5-236.sh
> +    install  kit/manifake "${PREFIX}/bin/"
double space

2021-05-25 21:58 UTC, merged