Use the new repository URL for stage0-posix.
fosslinux/live-bootstrap pull request #127
Opened 2021-06-22 20:19 UTC by stikonas

2021-06-28 07:47 UTC, fosslinux requested changes

2021-06-28 07:48 UTC, fosslinux commented on sysa/perl-5.6.2/files/config.sh
> +libpth='/image/lib/musl'
wait i see

2021-06-28 07:48 UTC, fosslinux requested changes

2021-06-28 07:48 UTC, fosslinux commented on parts.rst
> +is a depdendency of GNU Guile.
dependency*

2021-06-29 00:46 UTC, fosslinux approved these changes

2021-06-29 16:50 UTC, closed without merging

2021-06-29 16:51 UTC, stikonas commented
Merged