Guile deps
fosslinux/live-bootstrap pull request #129
Opened 2021-07-04 00:32 UTC by stikonas

These are dependencies needed for Guile 3.0.7.

I have a Guile build (with psyntax-pp boostrap) too but at the moment 2 files are not reproducible.

2021-07-04 05:52 UTC, fosslinux requested changes
Still need to look over for pregened files but a quick look doesn't look too problematic.

2021-07-04 05:52 UTC, fosslinux commented on sysa/gc-8.0.4/gc-8.0.4.sh
> +	CFLAGS='-D_GNU_SOURCE -DNO_GETCONTEXT -DSEARCH_FOR_DATA_START -DUSE_MMAP -DHAVE_DL_ITERATE_PHDR'
4 space indentation?

2021-07-04 05:52 UTC, fosslinux commented on sysa/gcc-4.7.4/pass1.sh
> +        make -C build/$dir LIBGCC2_INCLUDES=-I"${PREFIX}/include" STMP_FIXINC= GMPLIBS="-lmpc -lmpfr -lgmp" MAKEINFO=true
Indentation, also line breaks?

2021-07-04 05:52 UTC, fosslinux commented on sysa/libatomic_ops-7.6.10/libatomic_ops-7.6.10.sh
> +	--disable-shared
Indentation

2021-07-04 10:44 UTC, stikonas commented
Fixed raised issues. Yeah, most of this software is non-GNU, so somehow have fewer pre-gen files. GCC is the biggest one here but it's more or less the same as GCC 4.0.4. There are some issues while rebuilding some configure files in GCC for now (probably need to fix aclocal parameters) but they are in the directories that we don't use for C only build. Once we do full GCC with C and C++ backends, we can fix those issues and backport it here.

2021-07-04 19:31 UTC, andriuss-xilinx commented
I've resolved Guile reproducibility problems, so adding it too to this PR.

2021-07-04 19:33 UTC, stikonas commented
I've resolved Guile reproducibility issues, so adding it to this PR too.

2021-07-05 18:11 UTC, stikonas commented
Let's postpone the merge in the short term. We can merge this later. I'll cherry-pick download function fix though.

2021-07-06 22:37 UTC, stikonas commented
Closing this for now. Some commits will be incorporated into musl_trippled PR, let's do rest of Guile after g++ (it will let us drop some patches too).

2021-07-06 22:37 UTC, closed without merging