Musl triplet
fosslinux/live-bootstrap pull request #130
Opened 2021-07-06 22:55 UTC by stikonas

Add GCC 4.7.4 from the other PR and switch to i386-unknown-linux-musl prefix.

I'll remove gperf generated headers in the followon PR when I add g++.

2021-07-07 01:06 UTC, stikonas commented
Actually this on its own doesn't help (because *linux* is also caught to be gnu-linux rather than generic). I'll have to patch `libstdc++/configure.host` to solve that. In the meantime we can still switch to `i386-unknown-linux-musl` since that's the toolchain we actually have.

2021-07-09 23:16 UTC, fosslinux requested changes

2021-07-09 23:16 UTC, fosslinux commented on sysa/gcc-4.7.4/gcc-4.7.4.sh
> +    for dir in $(ls */Makefile.am | sed 's#/Makefile.am##' | tr "\n" " " | sed -e 's/ $/\n/' -e 's/^boehm-gc //'); do
Maybe add a quick explaining comment on what this massive `$()` is doing.

2021-07-09 23:16 UTC, fosslinux commented on sysa/gcc-4.7.4/patches/libstdc++-v3_musl.patch
> +Add support for *-linux-musl tripplet
triplet*

2021-07-09 23:16 UTC, fosslinux commented on sysa/gperf-3.1/gperf-3.1.sh
> +	cd ..
indentation

2021-07-09 23:25 UTC, stikonas commented on sysa/gcc-4.7.4/gcc-4.7.4.sh
> +    for dir in $(ls */Makefile.am | sed 's#/Makefile.am##' | tr "\n" " " | sed -e 's/ $/\n/' -e 's/^boehm-gc //'); do
Ok, I've added a comment and a brief explanation why boehm-gc is excluded (it was failing but boehm-gc is not used). In principle it would be nicer to clear up this autotools regeneration in the future, it's slightly insane and hacky right now.

2021-07-15 10:40 UTC, fosslinux approved these changes

2021-07-15 10:40 UTC, fosslinux commented on sysa/gcc-4.7.4/gcc-4.7.4.sh
> +    # and error but we don't use that directory anyway (it's only needed for Objective C)
an*

2021-07-15 10:40 UTC, fosslinux commented on sysa/bash-5.1/bash-5.1.sh
> +    # build needed for reproducibility
`--build argument needed`... just for clarity

2021-07-15 10:40 UTC, fosslinux commented on sysa/gcc-4.7.4/gcc-4.7.4.sh
> +    # Pre-build texinfo files
Pre-built

2021-07-15 10:40 UTC, fosslinux commented on sysa/gcc-4.7.4/gcc-4.7.4.sh
> +    # Pre-build texinfo files
Pre-built

2021-07-15 17:00 UTC, merged