Packaging
fosslinux/live-bootstrap pull request #145
Opened 2022-01-20 23:43 UTC by fosslinux

All the preparations and actual implementations of packaging that are required for live-bootstrap.

INCOMPLETE:

- [ ] QEMU mode is mostly untested
- [ ] Various reproducibility issues unearthed by checksumming all files
- [ ] Likely to encounter disk space issues again in QEMU/hardware

2022-01-29 12:32 UTC, stikonas commented on sysa/tar-1.12/checksums
> +3d67caa46470a7c1f3b00b8301977bc1093fab333943aabfd84afaa1bd77a609  /usr/bin/tar
I'm getting `efde53cec77c2e0efb0cd2f747c4d649ffd16c12c69bf2dd42b6bf14926323a1`

2022-01-29 13:11 UTC, stikonas commented
You might already be aware but `autoconf-2.12_0.tar.gz`, `autoconf-2.13_0.tar.gz`, `musl-1.1.24_2.tar.gz` packages are empty. Not sure what's going on.

2022-03-07 18:04 UTC, stikonas requested changes
```
perl-5.6.2: creating package.
perl-5.6.2: checksumming created package.
perl-5.6.2_0.links: OK
perl-5.6.2_0.tar.gz: FAILED
sha256sum: WARNING: 1 of 2 computed checksums did NOT match
Subprocess error
ABORTING HARD
```

2022-03-09 18:42 UTC, stikonas requested changes

2022-03-09 18:42 UTC, stikonas commented on sysa/sed-4.0.9/checksums/pass1
> -a29789a4a0150cbc7ed718ece238cad4c3863c794c8825f0743bc6cf1838b4a8  /usr/bin/sed
Still expected by kaem script

2022-03-09 18:42 UTC, stikonas commented on sysa/tcc-0.9.27/checksums/tcc-0.9.27
> -287056807b7cd70ecded9201ef7afa0d71fb1cd1e4effc24e38aaf7580c5e442  /usr/bin/tcc
Still used by kaem script.

2022-03-09 18:42 UTC, stikonas commented on sysglobal/SHA256SUMS.pkgs
> +9f22b86ff9fcb90325e954f3850835c607f5e63b992275041886f25f4cd7169a  guile-3.0.7_0.x86.xbps
Something has to be done about chroot mode. The checksum is not stable there.

Or should comment guile out from `run.sh`? It has no immediate use right now.

2022-03-09 18:42 UTC, stikonas commented on sysglobal/helpers.sh
> +            tar --no-recursion --null -T /tmp/filelist.txt -cf "/usr/src/repo/${pkg}_${revision}.tar"
I think I saw some non-critical errors from this line, something like 
/tmp/filelists.txt file not found

2022-03-09 18:42 UTC, stikonas commented
Maybe it would be good to make missing file error fatal in sha256sum from mescc-tools-extra?

2022-03-12 14:08 UTC, stikonas commented
> Maybe it would be good to make missing file error fatal in sha256sum from mescc-tools-extra?

I've pushed the change to mescc-tools-extra. Maybe you can incorporate it into this PR?

2022-03-13 12:58 UTC, stikonas requested changes

2022-03-13 12:58 UTC, stikonas commented on sysc/guile-3.0.7/guile-3.0.7.sh
> +	    --build=i386-unknown-linux-musl \
whitespace (tab instead of spaces)

2022-03-13 16:22 UTC, stikonas commented on sysglobal/helpers.sh
> +fake_grep() {
What do you think about moving

`if command -v grep >/dev/null 2>&1; then` into `fake_grep` function (and possibly rename it, e.g. to `grep_wrapped`).
I.e. this function will check if `grep` is available and use that, else will fallback to what we currently have here.

Then, elsewhere in `helpers.sh` we just use `fake_grep` unconditionally.

2022-03-13 16:26 UTC, stikonas commented on sysglobal/helpers.sh
> +    fi
Consider moving this into a separate function. Aand maybe even split it into smaller functions.

2022-03-13 16:28 UTC, stikonas commented on sysglobal/helpers.sh
> +    fi
Probably should go into a separate function too. I think `build` function should contain simple steps only, so that anybody who looks into it would immediately have high-level idea what it is doing. And if somebody wants details, they should be in functions.

2022-04-04 21:01 UTC, stikonas commented on sysglobal/helpers.sh
> +    fi
Same here, `grep` needs to be protected with `command -v`

2022-04-05 08:39 UTC, fosslinux commented on sysglobal/helpers.sh
> +    if touch --help | grep ' \-h' >/dev/null; then
Before we have new touch, we have grep. Hence, there are three possible ways this construct can go.

1. Fails due to a lack of grep
2. Fails due to a lack of -h argument
3. Succeeds

Either way it does not matter so I omitted it for brevity. However, there is no harm in adding the `command -v grep` for clarity.

2022-04-05 08:42 UTC, fosslinux commented on sysglobal/helpers.sh
> +    fi
Same idea as above however here I think that it adds unnecessary complexity to add the grep check.

2022-04-05 17:43 UTC, stikonas commented on sysglobal/helpers.sh
> +    # If grep is unavaliable, then tar --sort is unavaliable.
```suggestion
    # If grep is unavailable, then tar --sort is unavailable.
```

2022-04-05 18:25 UTC, merged