sysgeneral: instruct tar to unlink files before creating them
fosslinux/live-bootstrap pull request #152
Opened 2022-04-24 19:18 UTC by bauen1

Discovered when building using unshare and no tmpfs, resulting in `/usr/bin/automake-1.4`, `/usr/bin/automake-1.6` and `/usr/bin/automake` all being hardlinked together.

2022-04-24 20:07 UTC, stikonas requested changes
Fails when installing tar-1.34

2022-04-25 03:53 UTC, fosslinux commented
Could you elaborate on the problem being solved here? I'm not really sure how this happens, as I ran into this with symlinks so I added this workaround https://github.com/fosslinux/live-bootstrap/pull/152/files#diff-bb3655625ec3a00693f39b72442d345b962ebafafe06d36cb6cff6dc6ba4e566R291 (unlink-first is probably a better solution, but I didn't know of it when I added that workaround).

2022-04-25 11:11 UTC, bauen1 commented
failure during tar-1.34:

```
tar-1.34: creating package.
tar-1.34: checksumming created package.
tar-1.34: cleaning up.
tar-1.34: installing package.
tar: ./usr: Cannot unlink: Directory not empty
tar: ./usr/bin: Cannot unlink: Directory not empty
tar: ./usr/libexec: Cannot unlink: Directory not empty
tar: ./usr/share: Cannot unlink: Directory not empty
tar: ./usr/share/man: Cannot unlink: Directory not empty
tar: ./usr/share/man/man1: Cannot unlink: Directory not empty
tar: ./usr/share/man/man8: Cannot unlink: Directory not empty
tar: Exiting with failure status due to previous errors
```

2022-05-01 23:14 UTC, stikonas requested changes
`./rootfs -c` failed for me with

```
make[1]: Leaving directory `/sysa/automake-1.6.3/build/automake-1.6.3/tests'
automake-1.6.3: creating package.
automake-1.6.3: checksumming created package.
automake-1.6.3_2.links: OK
automake-1.6.3_2.tar.bz2: FAILED
sha256sum: WARNING: 1 of 2 computed checksums did NOT match
Subprocess error
```

2022-05-02 08:32 UTC, fosslinux commented
Just needs checksum update as stikonas noted above. Otherwise LGTM

2022-05-03 00:04 UTC, stikonas commented
Merged after updating checksums.

2022-05-03 00:04 UTC, closed without merging