add CI-mode for later continuous integration: ./roots ci
fosslinux/live-bootstrap pull request #17
Opened 2021-01-18 10:54 UTC by bittorf

The basic idea is to rely on an external script,
which builds a kernel and includes our initrd.

We have now 3 possible calls:

```
./rootfs
./rootfs chroot
./rootfs ci
```

2021-01-18 11:02 UTC, fosslinux commented
All of this logic belongs in `.cirrus.yml` once my CI PR is merged. Hence, waiting on  #3.

2021-01-18 11:57 UTC, bittorf commented
IMHO it is better to keep the affinity to `cirrus` as low a possible.
Also think about those users, which want to test locally.

`.cirrus.yml` can not be run an my computer...

2021-01-19 00:03 UTC, fosslinux commented
In that case, then it should not be called `ci`. If we are not using it for only CI, then it needs to not be called CI in rootfs.sh.

2021-01-19 06:57 UTC, bittorf commented
Please propose another name for Argument 1.
I need an easy way to start qemu (later also for other architectures).

2021-01-19 08:33 UTC, fosslinux commented
1. We will not be using github actions. It does not have nested KVM support. And it is not as simple as just starting one command, we need to install dependencies, etc.
2. We already have an easy way to start qemu, `./rootfs.sh`.
3. We could use `minikernel`?

2021-01-19 11:14 UTC, fosslinux requested changes

2021-01-19 11:15 UTC, fosslinux commented on rootfs.sh
> +		git clone --depth 1 https://github.com/bittorf/kritis-linux.git
Also please checkout a specific commit here for reproducibility

2021-01-19 17:16 UTC, bittorf commented
ok, i have applied all your suggestions.

2021-01-19 22:30 UTC, fosslinux commented on rootfs.sh
> +			--log "$(pwd)/ci.log"
Just this one left, please either add logging to all of them or remove logging from this one.

2021-01-19 22:31 UTC, fosslinux commented
Please rename the commit to more accuratley reflect the changes being made, something like `Add new minikernel rootfs.sh build target` is good.

2021-01-20 07:46 UTC, bittorf commented
i have changed to commit text.

2021-01-20 08:00 UTC, fosslinux commented
Please rebase with master, and fix the logging problem (either standardize a log across all of them or remove the log).

2021-01-20 10:10 UTC, bittorf commented
rebased and unified LOGFILE

2021-01-20 22:52 UTC, merged