Network
fosslinux/live-bootstrap pull request #178
Opened 2022-05-30 11:41 UTC by fosslinux

Add the ability to download files from the network.

Still todo (but not in this already large PR)
- be able to custom specify mirror server to download from (as stikonas requested)
- static ips. only dhcp ips are currently supported through dhcp.

All previous behaviour has been retained as an option.

Not all testing is 100% complete.

All before curl rebuild with openssl must be http only. This lead to a few tarball changes.

2022-06-11 11:40 UTC, stikonas commented on sysa/curl-7.83.0/patches/help.patch
> +diff --color -ru src/Makefile.inc src/Makefile.inc
SPDX header and a comment with explanation why this is needed

2022-06-11 11:40 UTC, stikonas commented on sysa/curl-7.83.0/files/sinus.pl
> +my $pi = 3.1415;
SPDX header

2022-06-11 11:41 UTC, stikonas commented on sysc/curl-7.83.0/files/sinus.pl
> +my $pi = 3.1415;
SPDX header

2022-06-11 11:41 UTC, stikonas commented on sysc/curl-7.83.0/patches/help.patch
> +diff --color -ru src/Makefile.inc src/Makefile.inc
same as in sysa, spdx header and comment

2022-06-11 13:36 UTC, stikonas approved these changes
Looks good. There might be a few improvements possible but maybe better to split them into separate PRs.
* TODOs that are already mentioned here (mirror, etc).
* If possible move openssl and curl rebuild as early as possible in sysc (unless openssl depends on something late).

2022-06-11 14:27 UTC, stikonas requested changes

2022-06-11 14:27 UTC, stikonas commented on sysc.py
> +        self.get_file("https://master.dl.sourceforge.net/project/curl.mirror/curl-7_83_0/curl-7.83.0.tar.xz?viasf=1")
Can we output this into a nicer location?

2022-06-11 15:06 UTC, stikonas requested changes
When running `./rootfs.py -bw --external-sources` I get some errors like

```
cp: cannot open `/sysc/sys/kernel/slab/:A-0000128/trace' for reading: Permission denied
cp: cannot open `/sysc/sys/kernel/slab/:A-0000128/reclaim_account' for reading: Permission denied
cp: cannot open `/sysc/sys/kernel/slab/:A-0000128/order' for reading: Permission denied
cp: cannot open `/sysc/sys/kernel/slab/:A-0000128/object_size' for reading: Permission denied
cp: cannot open `/sysc/sys/kernel/slab/:A-0000128/shrink' for reading: Permission denied
cp: cannot open `/sysc/sys/kernel/slab/:A-0000128/hwcache_align' for reading: Permission denied
cp: cannot open `/sysc/sys/kernel/slab/:A-0000128/objs_per_slab' for reading: Permission denied
cp: cannot open `/sysc/sys/kernel/slab/:A-0000128/partial' for reading: Permission denied
cp: cannot open `/sysc/sys/kernel/slab/:A-0000128/slabs_cpu_partial' for reading: Permission denied
cp: cannot open `/sysc/sys/kernel/slab/:A-0000128/ctor' for reading: Permission denied
cp: cannot open `/sysc/sys/kernel/slab/:A-0000128/slab_size' for reading: Permission denied
cp: cannot open `/sysc/sys/kernel/slab/:A-0000128/cache_dma' for reading: Permission denied
cp: cannot create special file `/sysc_image//usr/src/sys/kernel/security/apparmor/.null': Operation not permitted
```
(more is printed but I truncated it)

2022-06-13 01:54 UTC, fosslinux commented on sysc.py
> +        self.get_file("https://master.dl.sourceforge.net/project/curl.mirror/curl-7_83_0/curl-7.83.0.tar.xz?viasf=1")
oh I will just outright remove the `?viasf=1` now as `-L` added to curl which follows redirects (which is why it was there in first place).

2022-06-13 16:54 UTC, stikonas requested changes
just a couple of minor points.

2022-06-13 16:54 UTC, stikonas commented on rootfs.py
> -                     '--clearenv',
Why are we removing `clearenv`? I think it can be readded.

2022-06-13 16:54 UTC, stikonas commented on sysc.py
> +        self.get_file("https://github.com/void-linux/xbps/archive/refs/tags/0.59.1.tar.gz")
Hmm, it's a bit ugly to download tarball into `0.59.1.tar.gz`. `xbps-0.59.1.tar.gz` was nicer.

2022-06-17 23:01 UTC, fosslinux commented on sysc.py
> +        self.get_file("https://github.com/void-linux/xbps/archive/refs/tags/0.59.1.tar.gz")
I agree, but there's not really any mechanism to change the output filename when downloaded in sysc right now (nor can I figure out an elegant solution). We can look into that a bit later

2022-06-17 23:04 UTC, stikonas commented on sysc.py
> +        self.get_file("https://github.com/void-linux/xbps/archive/refs/tags/0.59.1.tar.gz")
Ok, let's merge it like this then. Maybe add a `TODO` comment and merge?

2022-06-18 09:51 UTC, merged