Coreutils update
fosslinux/live-bootstrap pull request #19
Opened 2021-01-21 21:36 UTC by stikonas

2021-01-21 23:39 UTC, fosslinux requested changes
A readme bit would also be neat.

2021-01-21 23:39 UTC, fosslinux commented on sysa/heirloom-devtools-070527/heirloom-devtools-070527.kaem
> +make -f Makefile.mk CC=tcc AR=tcc\ -ar CFLAGS+=-I.\ -DMAXPATHLEN=100\ -DEILSEQ=84\ -DMB_LEN_MAX=100\ -Dswprintf=sprintf\ -Dwcslen=strlen\ -Diswdigit=isdigit\ -Diswxdigit=isxdigit\ -Diswlower=islower\
Split on `\`?

2021-01-21 23:42 UTC, stikonas commented on sysa/heirloom-devtools-070527/heirloom-devtools-070527.kaem
> +make -f Makefile.mk CC=tcc AR=tcc\ -ar CFLAGS+=-I.\ -DMAXPATHLEN=100\ -DEILSEQ=84\ -DMB_LEN_MAX=100\ -Dswprintf=sprintf\ -Dwcslen=strlen\ -Diswdigit=isdigit\ -Diswxdigit=isxdigit\ -Diswlower=islower\
Ok, I can split.

As for `README`, I thought we should finish at least both heirloom `lex` and `yacc` and then describe both in one paragraph.

If you want I can write now, but I thought it's better to wait until we are done with `lex`.

2021-01-21 23:50 UTC, stikonas commented on sysa/heirloom-devtools-070527/heirloom-devtools-070527.kaem
> +make -f Makefile.mk CC=tcc AR=tcc\ -ar CFLAGS+=-I.\ -DMAXPATHLEN=100\ -DEILSEQ=84\ -DMB_LEN_MAX=100\ -Dswprintf=sprintf\ -Dwcslen=strlen\ -Diswdigit=isdigit\ -Diswxdigit=isxdigit\ -Diswlower=islower\
Hmm, splitting lines in kaem is a bit tricky. I tried to add `\` at the end of the line and no spaces on the next line but it still didn't work...

2021-01-22 08:43 UTC, fosslinux commented on sysa/heirloom-devtools-070527/heirloom-devtools-070527.kaem
> +make -f Makefile.mk CC=tcc AR=tcc\ -ar CFLAGS+=-I.\ -DMAXPATHLEN=100\ -DEILSEQ=84\ -DMB_LEN_MAX=100\ -Dswprintf=sprintf\ -Dwcslen=strlen\ -Diswdigit=isdigit\ -Diswxdigit=isxdigit\ -Diswlower=islower\
Lol forgot it was kaem. Please just remove the `\` then.

2021-01-22 08:44 UTC, fosslinux commented
regarding README, yeah, we can just describe both in one para later.

2021-01-22 18:44 UTC, stikonas commented
Ok, I think `yacc` hits some mes libc bug because when building on normal system with the same version of tinycc but with glibc it works.

2021-01-23 00:21 UTC, stikonas commented on sysa/heirloom-devtools-070527/heirloom-devtools-070527.kaem
> +make -f Makefile.mk CC=tcc AR=tcc\ -ar CFLAGS+=-I.\ -DMAXPATHLEN=100\ -DEILSEQ=84\ -DMB_LEN_MAX=100\ -Dswprintf=sprintf\ -Dwcslen=strlen\ -Diswdigit=isdigit\ -Diswxdigit=isxdigit\ -Diswlower=islower\
Agreed on IRC to keep it as it is.

2021-01-24 22:42 UTC, stikonas commented
Added lex too although at the moment it fails to compile.

Generated parse.c file contains tokens like

`# define C 257`
instead of
`# define CHAR 257`

and also
```
-static YYCONST yytabelem yyact[]={
+static YYCONST yytabelem y[]={
```

2021-01-26 21:36 UTC, stikonas commented
`yacc` is ready to go. Lex will be done in a follow-on PR.

2021-01-28 00:11 UTC, stikonas commented
Lex is now working too.

2021-01-28 01:59 UTC, merged