Change up how sources are defined
fosslinux/live-bootstrap pull request #207
Opened 2022-09-29 10:54 UTC by fosslinux

Currently we have sources defined in a very odd way.

- They are defined in the Python get scripts, checksums are in a separate file, and they are also defined in sysc separately.
- Tarballs have to be named to be the same as the package that they are a part of (which is a bit silly).
- Multiple sources isn't supported well.
- Non-tarball sources isn't supported at all.
- If the name of the directory is not the name of the package it needs to be manually specified.

With this system all of these problems are fixed and the sources are defined in a more specced way. This can be interpreted easily by any further tools and allows for significantly more flexibility.

2022-09-29 19:29 UTC, stikonas requested changes
Looks good in general, mostly changes in checksum-transcriber.c

2022-09-29 19:29 UTC, stikonas commented on sysa/checksum-transcriber.c
> +			// Occurs when there is only two tokens
```suggestion
			// Occurs when there are only two tokens
```

2022-09-29 19:29 UTC, stikonas commented on sysa/checksum-transcriber.c
> +			i = i + 1;
```suggestion
			line += 1;
			i += 1;
```

2022-09-29 19:29 UTC, stikonas commented on sysa/checksum-transcriber.c
> +			filename = filename + 1;
```suggestion
			filename += 1;
```

2022-09-29 19:29 UTC, stikonas commented on sysa/checksum-transcriber.c
> +		// TODO: read env variable (not sure how to do using M2libc)
I think you need to get it from `int main(int argc, char** argv, char** envp)`

2022-09-29 19:29 UTC, stikonas commented on sysa/run.kaem
> +M2-Mesoplanet --architecture ${ARCH} -f checksum-transcriber.c -o ${bindir}/checksum-transcriber
Should we check checksum of `checksum-transcriber`?

2022-09-29 19:29 UTC, stikonas commented on sysa/checksum-transcriber.c
> +	// Clean up
I wonder if we can also clean up `malloc`ed memory. Or is that too hard?

2022-09-29 19:29 UTC, stikonas commented on .reuse/dep5
>  # Copyright: $YEAR $NAME <$CONTACT>
Typo in commit message:
- This is also used to make sources avaliable and extract sources.
should be
- This is also used to make sources available and extract sources.
Also, do we need a keyword to close https://github.com/fosslinux/live-bootstrap/issues/188 ?

2022-09-30 12:37 UTC, fosslinux commented on sysa/checksum-transcriber.c
> +	// Clean up
free is NOP in M2libc anyway. But doesn't hurt anything to clean up

2022-09-30 12:39 UTC, stikonas commented on sysa/checksum-transcriber.c
> +	// Clean up
Yes, I saw that free is NOP. Though that might be something to rethink for UEFI.

2022-09-30 12:59 UTC, stikonas commented on sysa/checksum-transcriber.c
> +	// Clean up
Anyway, if it looks complicated to free everything then don't bother, we might have to go with cleanup in M2libc approach anyway, as other software (M2-Planet, hex2, M1, etc) doesn't clean up well either.

2022-09-30 23:52 UTC, fosslinux commented on sysa/checksum-transcriber.c
> +	// Clean up
All done now.

2022-10-01 22:56 UTC, stikonas approved these changes

2022-10-01 23:28 UTC, merged