Implement kernel bootstrap up to building Linux.
fosslinux/live-bootstrap pull request #253
Opened 2023-03-01 14:07 UTC by rick-masters

Resolves #252

2023-03-01 21:47 UTC, fosslinux requested changes
This is a first-pass review, there's some things I haven't really looked at in detail yet but there's a few larger architectural things;

1. I would like for `--kernel-bootstrap` to be the default, when QEMU is used. This is meant to be the default pathway. Then, if `--kernel` is given, *then* we can not use the fiwix/builder-hex0 stuff.
2. I apologise for not communicating this one earlier, as this has been on my mind for a while with this. I'd like, when running under Fiwix, for an initramfs *not* to be used (or, at least, used to the minimal extent possible - but from my relatively brief look over this it doesn't appear required). At minimum, it'd be great if all the packages could be build on-disk rather than in-ram (initramfs). This will allow live-bootstrap to be build on much lower memory machines and allow for sysa to be expanded without issue. builder-hex0 does look like it can write to/read from disk, but I'm not sure if that extends to the creation of an EXT filesystem on a disk?
3. This one is more of a question - what's the rationale for using builder-hex0 to start, instead of say, builder-hex0-mini? (it probably doesn't really matter, because both are hex0 anyway, but just wanted to hear your thoughts).

Thank you very much for this PR, I'm excited to get this in :tada:

2023-03-01 21:47 UTC, fosslinux commented on parts.rst
> +If the kernel-bootstrap option is enabled then the ``builder-hex0`` kernel boots from a hard drive and loads an enormous shell script which embeds files (loaded with the ``src`` command) and the init
can be compiled with any one of ....

Initially I thought that this meant you needed all of them to build it, and quickly realized that made no sense.

2023-03-01 21:47 UTC, fosslinux commented on sysa.py
> +        run('tar', '-c', '-z', '-p',
Is there a reason for tarring vs just appending every file? If it's required then so be it for now, but I'm not a huge fan of requiring tar on the host system.

2023-03-01 21:47 UTC, fosslinux commented on sysa/fiwix-1.4.0-lb1/sources
> +https://github.com/rick-masters/Fiwix/releases/download/v1.4.0-lb1/fiwix-1.4.0-lb1.tar.gz ff57d1fbf0547a27dec4d7146eb9c17d01158ca5886de54e5b9bac2bec473ef3
In the future, do you think the patchset will be small enough that we be able to either use an upstream release of Fiwix or apply any remaining patches within live-bootstrap? I'm don't really love using live-bootstrap specific forks, unless the number of patches is prohibitive.

2023-03-01 21:47 UTC, fosslinux commented on sysa/fiwix-1.4.0-lb1/fiwix-1.4.0-lb1.kaem
> +# SPDX-FileCopyrightText: 2021 Andrius Štikonas <andrius@stikonas.eu>
this should be you ;)

2023-03-01 21:47 UTC, fosslinux commented on sysa/fiwix-1.4.0-lb1/fiwix-1.4.0-lb1.kaem
> +    #cp ${pkg}.checksums ${srcdir}
Fine for draft, just a reminder to fix before merge

2023-03-01 21:47 UTC, fosslinux commented on sysa/lwext4-1.0.0-lb1/lwext4-1.0.0-lb1.kaem
> +./make_fiwix_initrd
I would prefer that this is run outside of the build script in `run.kaem` - build scripts should really only be doing compiling & installing.

2023-03-01 21:47 UTC, fosslinux commented on sysa/mes-0.24.2/simple-patches/mes-0.24.1.kaem-base-address.after
> +${mescc_scm} -- --base-address 0x08048000 -L
Can you add documentation for `simple-patches` subdir to `DEVEL.md`.

2023-03-01 21:50 UTC, fosslinux commented
Also, with your comment in #252, will this currently fail or do something else when transferring from fiwix -> linux?

Other thing I just thought of, architecturally I think it would be more consistent to split sysa into sysa and sysb, where sysa is builder-hex0 and sysb is fiwix, and then the current sysb  can be removed, since we have guranteed hard disk support in fiwix.

2023-03-02 23:58 UTC, stikonas commented on parts.rst
> +
Would it not be simpler to build curl at the end of sysa then? Obviously it wouldn't be able to run on fiwix, but then we can transfer curl binary (together with all other binaries that we already do) rather than special casing tarball transfer.

2023-03-03 15:25 UTC, rick-masters commented on parts.rst
> +
I'm rebuilding musl-1.2.3 with threads at the end of sysa but that version of musl-1.2.3 cannot be used because Fiwix does not support it. Unfortunately if a curl build is attempted `configure` will create test programs for threads that pick up the new musl and end up not working. Worse, they hang the build.

2023-03-03 15:30 UTC, rick-masters commented on sysa/fiwix-1.4.0-lb1/sources
> +https://github.com/rick-masters/Fiwix/releases/download/v1.4.0-lb1/fiwix-1.4.0-lb1.tar.gz ff57d1fbf0547a27dec4d7146eb9c17d01158ca5886de54e5b9bac2bec473ef3
It it my goal and hope that we can use an official release and then patch it. Unfortunately right now there are too many complicated patches. We only have simple-patch at that stage and it would be a lot of work to construct patches that way.

2023-03-03 15:31 UTC, rick-masters commented on sysa/lwext4-1.0.0-lb1/lwext4-1.0.0-lb1.kaem
> +./make_fiwix_initrd
This will be resolved in the next update.

2023-03-03 15:31 UTC, rick-masters commented on sysa/mes-0.24.2/simple-patches/mes-0.24.1.kaem-base-address.after
> +${mescc_scm} -- --base-address 0x08048000 -L
This will be resolved in the next update.

2023-03-03 15:32 UTC, stikonas commented on parts.rst
> +
Yes, makes sense. Oh well...

2023-03-03 17:58 UTC, rick-masters commented on sysa.py
> +        run('tar', '-c', '-z', '-p',
The usage of tar will be removed in the next update.

2023-03-03 18:28 UTC, rick-masters commented
@fosslinux 
For your other questions:
1. I will work on making removing `--kernel-bootstrap` and make it the default instead.
2. I will explore writing the ext2 image to disk instead of using a ram drive. This would mean overwriting the builder-hex0 srcfs disk image. One issue is that I believe it may exceed the size of a hard drive supported by a simple BIOS using Cylinder/Head/Sector calculations, at least with the current default qemu disk geometry. It might require LBA but I'm not sure.
3. I think it is a reasonable goal to start with something small like builder-hex0-mini that complies builder-hex0. The problem with the current design of builder-hex0-mini is that it writes the compiled binary to the start of disk and depends on a reboot to activate it. As with the transition to Fiwix I think a reboot can be avoided. This would take some work. I'd postpone this until after the initial integration.
4. There is currently no transition from Fiwix to Linux so the bootstrap stops soon after Linux is compiled. That may be a reason to postpone making `--kernel-bootstrap` the default initially until I can complete the Fiwix to Linux boot transition.

It is not very clear to me how a redesign with Fiwix as sysb would work exactly. Sysb is currently used for booting Linux (I think) so I don't see how that changes. (To be honest, I'm not sure I want to sign up for changing the method of booting Linux.) I think I'd need some more details to understand what you are suggesting.

It might be a while until I submit the next updated PR. I'm taking a breather to work at a more leisurely pace for a little while.

2023-03-03 20:50 UTC, stikonas commented
> @fosslinux For your other questions:
> 
>     2. I will explore writing the ext2 image to disk instead of using a ram drive. This would mean overwriting the builder-hex0 srcfs disk image. One issue is that I believe it may exceed the size of a hard drive supported by a simple BIOS using Cylinder/Head/Sector calculations, at least with the current default qemu disk geometry. It might require LBA but I'm not sure.

Perhaps it might be simpler to do something like this:
* builder-hex0 boots fiwix with ram drive.
* fiwix then has a hard drive support, so we then populate the hard drive and transition into another fwix.

This would add another kexec like transition but perhaps code can mostly be shared with fiwix to linux transition?

2023-03-03 21:59 UTC, fosslinux commented on sysa/fiwix-1.4.0-lb1/sources
> +https://github.com/rick-masters/Fiwix/releases/download/v1.4.0-lb1/fiwix-1.4.0-lb1.tar.gz ff57d1fbf0547a27dec4d7146eb9c17d01158ca5886de54e5b9bac2bec473ef3
Sounds good to me. Happy with this as-is in that case :)

2023-03-03 22:01 UTC, fosslinux commented
> I will explore writing the ext2 image to disk instead of using a ram drive. This would mean overwriting the builder-hex0 srcfs disk image. One issue is that I believe it may exceed the size of a hard drive supported by a simple BIOS using Cylinder/Head/Sector calculations, at least with the current default qemu disk geometry. It might require LBA but I'm not sure.

Sounds good. If you think that @stikonas method would be easier, or if two separate disks are used for builder-hex0 and fiwix, that's alright with me.

> I think it is a reasonable goal to start with something small like builder-hex0-mini that complies builder-hex0. The problem with the current design of builder-hex0-mini is that it writes the compiled binary to the start of disk and depends on a reboot to activate it. As with the transition to Fiwix I think a reboot can be avoided. This would take some work. I'd postpone this until after the initial integration.

No worries about this for the time being, then - this can come later, as you said.

> There is currently no transition from Fiwix to Linux so the bootstrap stops soon after Linux is compiled. That may be a reason to postpone making --kernel-bootstrap the default initially until I can complete the Fiwix to Linux boot transition.

Ah, ok. In my opinion, let's still make `--kernel-bootstrap` the default, but document/add warnings that `--kernel` should still be used for a full build. Happy to hear other thoughts though.

> It might be a while until I submit the next updated PR. I'm taking a breather to work at a more leisurely pace for a little while.

That is absolutely fine! It is good to spend some time for ourselves.

2023-03-04 17:17 UTC, rick-masters commented
@stikonas 

`fiwix then has a hard drive support, so we then populate the hard drive and transition into another fwix.`

I'm not sure this question matters yet. builder-hex0/BIOS may be able to write to a larger hard disk by using a bigger disk geometry. I just need to look into it. If not, maybe your Linux changes will save enough space. We need to save approx. 140MB to keep under the limit of the current geometry. (Which is 1024 cylinders * 32 heads * 63 sectors * 512 bytes/sector)

@fosslinux 
Note that eliminating a Fiwix ram drive does not reduce overall memory requirements. Currently builder-hex0 uses 3GB which is more than Fiwix. The usage is approx. 650MB for live-bootstrap distfiles and builds, 1152MB for the Fiwix ext2 image, 670MB for running processes, and 604MB for suspended processes. Even if the ext2 image is copied to disk it needs to be created in memory first (with the current design of builder-hex0.)

The vast majority of the 1.2GB for processes is for mes. I could eliminate half (the memory for suspended processes) by implementing virtual memory but I'm reluctant to add that complexity. Long term really getting memory down means redesigning or replacing mes, IMHO.

That said, there is a significant benefit to moving away from a Fiwix ram disk. My modification to Fiwix to support large ram drives was difficult/complex/messy and I'd rather not try to upstream it:
https://github.com/rick-masters/Fiwix/commit/747a76335a30d41ada7a7803f5ef917068199843

So, I'll continue to look at how to boot Fiwix off a hard drive. For the transition to Linux, I expect sysb/run.sh would need to be modified to do one of: format the first drive (overwriting sysa), format a second partition on the first drive,  or format a (or use a pre-formatted) second drive.

2023-03-06 06:22 UTC, fosslinux commented
>  Note that eliminating a Fiwix ram drive does not reduce overall memory requirements. Currently builder-hex0 uses 3GB which is more than Fiwix. The usage is approx. 650MB for live-bootstrap distfiles and builds, 1152MB for the Fiwix ext2 image, 670MB for running processes, and 604MB for suspended processes. Even if the ext2 image is copied to disk it needs to be created in memory first (with the current design of builder-hex0.)

This is not particularly problematic. If sysa is expanded or more packages are added, then the only added cost to RAM is distfiles & possibly the ext2 image. However, in the current state, we also need to have disk space available for the compilation process - this is where compiling large packages such as the Linux kernel can become very problematic. With Fiwix it seems we should be able to eliminate this problem.

> So, I'll continue to look at how to boot Fiwix off a hard drive. For the transition to Linux, I expect sysb/run.sh would need to be modified to do one of: format the first drive (overwriting sysa), format a second partition on the first drive, or format a (or use a pre-formatted) second drive.

If you can handle the Fiwix side, I'd be happy to do this bit.

2023-03-06 16:35 UTC, rick-masters commented
@fosslinux 
`With Fiwix it seems we should be able to eliminate this problem.`

I'm not sure how. If we need more space for compilation then the ext2 image needs to be expanded and since that is created in memory with builder-hex0, it expands the memory requirements. builder-hex0 is near usable memory limits already which is 3GB without implementing PAE.
Perhaps you are suggesting Fiwix could expand the ext2 file system once on disk or format another partition or disk?

2023-03-24 22:38 UTC, stikonas commented on sysa/kexec-fiwix/src/kexec-fiwix.c
> +		".byte 0xEA, 0x00, 0x40, 0x00, 0x00, 0x08, 0x00 \n\t"
Can you not use ljmp and let tcc convert it to machine code here instead of writing machine code directly?

2023-03-30 16:51 UTC, rick-masters commented on sysa/kexec-fiwix/src/kexec-fiwix.c
> +		".byte 0xEA, 0x00, 0x40, 0x00, 0x00, 0x08, 0x00 \n\t"
This will be resolved in the next update.

2023-04-02 04:59 UTC, fosslinux commented
superseded by #272

2023-04-02 04:59 UTC, closed without merging