Musl
fosslinux/live-bootstrap pull request #26
Opened 2021-02-03 00:57 UTC by andriuss-xilinx

tcc is build using normal bash script instead of bash build harness because it's mostly copy-paste from kaem file and also tcc has no tar.

2021-02-03 05:43 UTC, fosslinux requested changes
Could you please also add patch headers that (even just one sentence) explain why the patch is needed, this is very helpful for documentation. I am applying this to all other patches.

2021-02-03 05:43 UTC, fosslinux commented on README.md
> +#### Part 25 tcc 0.9.27 (musl)
Newline after.

2021-02-03 05:43 UTC, fosslinux commented on sysa/musl-1.1.24/musl-1.1.24.sh
> +    fi
Hm, maybe we should have a separate "create device node" stage, I think that makes more sense than doing this here.

2021-02-03 05:43 UTC, fosslinux commented on sysa/tcc-0.9.27/mes-libc-patched.kaem
> +# Recompile tcc using patched libc
Can we just move mes-libc-patched before tinycc-patched?

2021-02-03 05:43 UTC, fosslinux commented on sysa/tcc-0.9.27/tcc-musl.sh
> +for TCC in tcc-0.9.26 tcc-musl; do
Can you add a comment here soemthing along the lines of 

> We first have to recompile using tcc-0.9.26 as tcc-0.9.27 is not selfhosting, but when linked with musl it is.

2021-02-03 05:43 UTC, fosslinux commented on sysa/musl-1.1.24/patches/tcc_static.patch
> +diff -U3 -r src/internal/syscall.h src/internal/syscall.h
Patch header:

> tinycc does not support the use of the static keyword within an array length or index.

2021-02-03 05:47 UTC, fosslinux commented on sysa/run.sh
> +tcc-0.9.27/tcc-musl.sh
Also, can we use build here?

2021-02-03 15:21 UTC, pder commented on sysa/tcc-0.9.27/tcc-musl.sh
> +set -e
Could we do set -ex here?

2021-02-03 18:56 UTC, stikonas commented on README.md
> +#### Part 25 tcc 0.9.27 (musl)
fixed

2021-02-03 18:56 UTC, stikonas commented on sysa/tcc-0.9.27/mes-libc-patched.kaem
> +# Recompile tcc using patched libc
@pder promised to fix it since it's not my commit.

2021-02-03 18:57 UTC, stikonas commented on sysa/tcc-0.9.27/tcc-musl.sh
> +for TCC in tcc-0.9.26 tcc-musl; do
done

2021-02-03 19:00 UTC, stikonas commented on sysa/musl-1.1.24/patches/tcc_static.patch
> +diff -U3 -r src/internal/syscall.h src/internal/syscall.h
done

2021-02-03 19:01 UTC, stikonas commented on sysa/tcc-0.9.27/tcc-musl.sh
> +set -e
This script will be replaced with sourced script. So not needed

2021-02-03 19:02 UTC, stikonas commented on sysa/musl-1.1.24/musl-1.1.24.sh
> +    fi
musl's `./configure` seems to corrupt `/dev/null` node for some reason, so let's just create /dev here and populate it at some point later, maybe after `musl`.

2021-02-04 05:27 UTC, fosslinux commented on sysa/musl-1.1.24/musl-1.1.24.sh
> +    fi
Can you add a comment to that effect please? `# configure script needs these nodes but is not standard/corrupts them`

2021-02-04 05:28 UTC, fosslinux commented on sysa/musl-1.1.24/musl-1.1.24.sh
> +    fi
Wait nvm...

2021-02-04 05:30 UTC, fosslinux requested changes
Thanks!

2021-02-04 05:30 UTC, fosslinux commented on sysa/tcc-0.9.27/tcc-musl.sh
> +	mkdir -p ${libdir}/tcc
This can just go outside the loop.

2021-02-04 05:30 UTC, fosslinux commented on sysa/tcc-0.9.27/tcc-musl.sh
> +    rm ${bindir}/boot*-tcc ${bindir}/tcc-0.9.26 ${bindir}/mes-tcc
Can you comment here something like remove old tcc binaries.

2021-02-04 10:40 UTC, merged