Patch mk-ca-bundle to make ca-certificates reproducible regardless of current date
fosslinux/live-bootstrap pull request #269
Opened 2023-03-17 18:47 UTC by eduardosm

Supersedes https://github.com/fosslinux/live-bootstrap/pull/221.

Based on the tips from https://github.com/fosslinux/live-bootstrap/pull/221#issuecomment-1374610121.

Also updated ca-certificates package to the latest version (3.88.1)

2023-03-17 22:03 UTC, fosslinux commented
Could you please squash the first and last commit, and make the header say have your copyright (in SPDX-CopyrightHeader) instead of mine?

2023-03-17 22:31 UTC, eduardosm commented
> Could you please squash the first and last commit, and make the header say have your copyright (in SPDX-CopyrightHeader) instead of mine?

Done

2023-03-18 00:20 UTC, fosslinux requested changes
Only one small problem remaining

2023-03-18 10:47 UTC, eduardosm commented on sysc/ca-certificates-3.88.1/sources
> +https://ftp.mozilla.org/pub/security/nss/releases/NSS_3_88_1_RTM/src/nss-3.88.1.tar.gz 27d243edf87d1cf1bb9c861f03d387e0e9230ce5017f4308c941f558b54b3496
Makes sense, I hadn't thought of that. Changed and squashed into the second commit.

2023-03-18 19:08 UTC, stikonas approved these changes
Looks good.

Do we want to keep the second build of curl unpatched? I guess we won't have to do second build of ca-certificates...

2023-03-18 19:10 UTC, stikonas commented
One final thing: could you please add "Fixes #220" to the commit message of the last commit (on a separate line)

2023-03-18 19:38 UTC, eduardosm commented
> One final thing: could you please add "Fixes #220" to the commit message of the last commit (on a separate line)

Done

> Do we want to keep the second build of curl unpatched? I guess we won't have to do second build of ca-certificates...

I believe we are not even installing `mk-ca-bundle` in the second build.

The first build installs it with a dedicated `install` invocation.

https://github.com/fosslinux/live-bootstrap/blob/c0ea746ae534be8b07b32c353b59346c6beb1026/sysa/curl-7.83.0/curl-7.83.0.sh#L31-L34

The second build does not have a custom `src_install` defined.

2023-03-18 21:56 UTC, stikonas approved these changes
Will merge once CI finishes.

2023-03-19 00:18 UTC, merged