Add patch headers
fosslinux/live-bootstrap pull request #27
Opened 2021-02-03 06:04 UTC by fosslinux

Also cleanup the flex patch a bit

@stikonas  I need you to check if the reasons for all these patches are correct.

2021-02-03 06:04 UTC, fosslinux commented on sysa/coreutils-5.0/patches/mbstate.patch
> +This implementation was taken from musl.
Is this true @stikonas

2021-02-03 06:05 UTC, fosslinux commented on sysa/tcc-0.9.27/patches/mes-libc-qsort.patch
> +with larger string sizes.
@pder any other comments

2021-02-03 18:50 UTC, stikonas commented on sysa/coreutils-5.0/patches/mbstate.patch
> +This implementation was taken from musl.
No. I think I just took it from my system, so must be glibc 2.32.

2021-02-03 18:55 UTC, stikonas requested changes
`scan_l.patch` is essential (despite it only doing cosmetical changes).

`flex-tmp` (which uses lexer generated by `lex`) is not able to process unpatched file.
So we need to (cosmetically) patch scan.l first and compile new `flex`. That `flex` is then good enough and can self-host. Although, we don't rebuild it here since we need to build newer version anyway.

2021-02-03 20:12 UTC, stikonas requested changes
`scan_l.patch` is essential (despite it only doing cosmetical changes).

`flex-tmp` (which uses lexer generated by `lex`) is not able to process unpatched file.
So we need to (cosmetically) patch scan.l first and compile new `flex`. That `flex` is then good enough and can self-host. Although, we don't rebuild it here since we need to build newer version anyway.

2021-02-04 05:30 UTC, fosslinux commented
Huh, you seem to be right; that is quite odd, but that's ok.

2021-02-04 10:39 UTC, merged