Kernel bootstrap phase2 v1
fosslinux/live-bootstrap pull request #295
Opened 2023-05-10 17:29 UTC by rick-masters

Resolves #294

2023-05-11 05:27 UTC, fosslinux reviewed
Small things only. I'm very happy with the implementation in general!

2023-05-11 05:27 UTC, fosslinux commented on parts.rst
> +A kernel bootstrapping option is used by default at the beginning. The tiny ``builder-hex0-x86-stage1`` binary seed boots, builds and runs the ``builder-hex0-x86-stage2`` kernel. The stage2 kernel ha
can you note that all `builder-hex0` kernels are written in hex0? I know this seems obvious, but just for the sake of absolute clarity.

2023-05-11 05:27 UTC, fosslinux commented on parts.rst
> +If chroot or bwrap is specified or if a pre-existing kernel is provided for QEMU then we start with the two raw binary seeds ``hex0-seed`` and ``kaem-optional-seed``. We use those seeds to rebuild th
remove "for QEMU" - QEMU is not special in this regard, it could be bare metal or anything else

2023-05-11 05:27 UTC, fosslinux commented on parts.rst
> +By default (when kernel bootstrap is enabled), the ``builder-hex0-x86-stage1`` boot loader/compiler boots from a hard drive and loads hex0 source code from disk, compiles, and runs the builder-hex0-x
very small nit: consistency in terms of code blocks vs plain text, and capitalization

2023-05-11 05:27 UTC, fosslinux commented on sysa.py
> +            image_file.write(b'\xAA')
What's the purpose of this? (a comment to the effect of whatever the answer is would be great)

2023-05-16 22:22 UTC, stikonas commented on sysa.py
> +            image_file.write(b'\xAA')
See also comment in https://github.com/oriansj/bootstrap-seeds/pull/39#issuecomment-1550228515 Maybe it would be good to provide 2 bins? One is 200 byte binary and the other 512 byte binary with MBR signature?

2023-05-17 12:35 UTC, rick-masters commented on parts.rst
> +A kernel bootstrapping option is used by default at the beginning. The tiny ``builder-hex0-x86-stage1`` binary seed boots, builds and runs the ``builder-hex0-x86-stage2`` kernel. The stage2 kernel ha
This will be resolved in the next update.

2023-05-17 12:36 UTC, rick-masters commented on parts.rst
> +If chroot or bwrap is specified or if a pre-existing kernel is provided for QEMU then we start with the two raw binary seeds ``hex0-seed`` and ``kaem-optional-seed``. We use those seeds to rebuild th
This will be resolved in the next update.

2023-05-17 12:36 UTC, rick-masters commented on parts.rst
> +By default (when kernel bootstrap is enabled), the ``builder-hex0-x86-stage1`` boot loader/compiler boots from a hard drive and loads hex0 source code from disk, compiles, and runs the builder-hex0-x
This will be resolved in the next update.

2023-05-18 10:44 UTC, rick-masters commented on sysa.py
> +            image_file.write(b'\xAA')
This code will be removed in the next update. It was for padding the boot code to fill a sector and including the MBR signature. The stage1 boot code is now padded in advance. Also, the next update pulls stage1 from stage0-posix.

2023-05-18 20:10 UTC, stikonas requested changes
Looks good in general but a few minor comments

2023-05-18 20:10 UTC, stikonas commented on sysa/kexec-linux/src/kexec-linux.c
> +	       );
Why can't we just call libc function `sync()` from `unistd.h`?

2023-05-18 20:10 UTC, stikonas commented on sysa/kexec-linux/src/kexec-linux.c
> +	       );
Could we use
`syscall(SYS_reboot, int magic, int magic2, int cmd, void *arg)` or maybe even `int reboot(int type)`

2023-05-18 20:10 UTC, stikonas commented on sysa/lwext4-1.0.0-lb1/files/make_fiwix_initrd.c
> +	printf("ext4_mknod /mp/dev/ram0\n");
`puts`?

2023-05-19 18:42 UTC, rick-masters commented on sysa/kexec-linux/src/kexec-linux.c
> +	       );
Yes, this can be done but to do this I need to do something I should have done in the first place.
I'll need to compile kexec-linux later in the build with gcc+musl instead of early with tcc+mes/lib.
The reason I compile it early was because it was easy to copy the kexec-fiwix kaem scripts and because, as a small utility program, it didn't fit the helpers.sh/build process used later on for packages.
However, it can be built by manually with a small bash script. It might stick out a bit in run2.sh but I think its more correct than what I'm doing now because it will be built closer to where it is used and will allow using the library calls you have suggested.
I have this working and my next update will include this change.

2023-05-19 19:51 UTC, stikonas commented on sysa/kexec-linux/src/kexec-linux.c
> +	       );
You can just put `gcc` command into `kexec-linux.sh` script in `src_compile()` function and I think it will just work. And then you also need `src_install()` step that copies it to "${DESTDIR}${PREFIX}/bin/".

2023-05-19 20:21 UTC, rick-masters commented on sysa/kexec-linux/src/kexec-linux.c
> +	       );
I can try to use the build command but I'll need to build a package with a version number because there is no way to opt out of that. I'm not sure its worth it as the package is unlikely to be used outside live-bootstrap. But I'll start working on it if you think it makes sense.

2023-05-19 20:23 UTC, stikonas commented on sysa/kexec-linux/src/kexec-linux.c
> +	       );
Oh yes, that's a limitation of `helpers.sh`. Perhaps you can just use dummy version, e.g. `kexec-linux-1`

2023-05-20 00:57 UTC, fosslinux commented on sysa/kexec-linux/src/kexec-linux.c
> +	       );
Version also makes sense because of `--repo`. The version doesn't need to be significant, it can just be incremented when there's a change.

2023-05-20 15:23 UTC, rick-masters commented on sysa/kexec-linux/src/kexec-linux.c
> +	       );
This should be resolved. kexec-linux is a package in the recent update.

2023-05-20 15:24 UTC, rick-masters commented on sysa/lwext4-1.0.0-lb1/files/make_fiwix_initrd.c
> +	printf("ext4_mknod /mp/dev/ram0\n");
puts is used where possible in the recent update.

2023-05-20 15:41 UTC, rick-masters commented on sysa/kexec-linux/src/kexec-linux.c
> +	       );
sync() is now used.

2023-05-20 16:34 UTC, stikonas commented on sysa/kexec-linux-1.0.0/files/kexec-linux.c
> +		fwrite(&stats.st_size, 4, 1, ramdrive_file);
is this change `sizeof() -> 4` intentional?

2023-05-20 16:34 UTC, stikonas approved these changes

2023-05-20 17:07 UTC, rick-masters commented on sysa/kexec-linux-1.0.0/files/kexec-linux.c
> +		fwrite(&stats.st_size, 4, 1, ramdrive_file);
Yes, this must be a 32 bit integer because that is what Fiwix reads from the ram drive. This code does make a little-endian assumption for larger integers but it works. I probably should have cast stats.st_size to a uint32_t variable before writing. I can make that change ... but it might take a couple hours to test and generate new checksum.

2023-05-20 17:32 UTC, stikonas commented on sysa/kexec-linux-1.0.0/files/kexec-linux.c
> +		fwrite(&stats.st_size, 4, 1, ramdrive_file);
I guess let's keep it like that then.

2023-05-20 17:45 UTC, rick-masters commented on sysa/kexec-linux-1.0.0/files/kexec-linux.c
> +		fwrite(&stats.st_size, 4, 1, ramdrive_file);
Well I've coded an improvement using a cast to uint32_t. It is more portable although big-endian usage seems pretty unlikely. I'm willing to submit it later after testing if this PR is still open.

2023-05-20 17:48 UTC, stikonas commented on sysa/kexec-linux-1.0.0/files/kexec-linux.c
> +		fwrite(&stats.st_size, 4, 1, ramdrive_file);
Sure feel free to submit it, we haven't merge it yet, though I guess we are close to being done here. I'm also running some testing now...

2023-05-21 00:13 UTC, stikonas approved these changes

2023-05-21 00:25 UTC, stikonas commented
Anyway, looks good, let's merge it and any further improvements can be added with the follow-on PRs.

2023-05-21 00:26 UTC, merged