add download cache
fosslinux/live-bootstrap pull request #30
Opened 2021-02-05 14:50 UTC by bittorf

overload 'wget' with a function,
so all wget downloads are cached in
ether '/tmp/cachedir-live-bootstrap' or
ENV defined using $CACHEDIR

2021-02-06 21:55 UTC, fosslinux requested changes
Please also rebase.

2021-02-06 21:55 UTC, fosslinux commented on rootfs.sh
> +	local dir="$GITDIR/sources/dl"
No need for the `/dl` IMO..

2021-02-06 21:55 UTC, fosslinux commented on rootfs.sh
> +	local url="$1"				# e.g. https://server/foo/bar.tgz
I really don't like all of these `# e.g.` comments, something that is unclear should be clearly explained in a comment above.

2021-02-06 21:55 UTC, fosslinux commented on rootfs.sh
> +	test -d "$CACHEDIR" && dir="$CACHEDIR"
instead of doing this you can just set dir to `${CACHEDIR:-${GITDIR}/sources}`

2021-02-06 21:55 UTC, fosslinux commented on rootfs.sh
> +	file="$( basename "$url" )"		# e.g. bar.tgz
remove spaces around the basename call

2021-02-06 21:55 UTC, fosslinux commented on rootfs.sh
> +		mkdir -p "$dir"
This can be moved outside of the if/else block.

2021-02-06 21:55 UTC, fosslinux commented on rootfs.sh
> +	test $? -eq 0 && checksum_do "$dir" "$file"
If the file already exists (line 28) I would want the checksumming to happen, and then if the checksumming fails, remove the file and attempt a redownload. This allows us to fix partial downloads that were CTRL-C'd. Then the entire checksumming process should be redone after as it is here.

2021-02-06 21:55 UTC, fosslinux commented on rootfs.sh
> +	test $? -eq 0 && checksum_do "$dir" "$file"
No need to test that `$? -eq 0`, we are running with `-e`, please unconditionally checksum.

2021-02-06 21:55 UTC, fosslinux commented on rootfs.sh
> +export GITDIR="$PWD"
On top of this, it would be good to check that we really are running rootfs.sh from the git dir. A quick test that "${GITDIR}/rootfs.sh" exists is not a bad idea, and error out with "rootfs.sh must be run from the base of the repo".

2021-02-06 21:55 UTC, fosslinux commented on rootfs.sh
> +checksum_do()
A much simpler implementation of this function could:

set file to the file to be checked (no need for dir)
set checksum_file (or store or whatever) to the path to the sha256sum file
something like:
```
# get the appropriate line from the checksum file, but..
if ! checksum="$(grep "$(basename ${file}")"; then
    # if it is not there, error out
    echo "There is no checksum for ${file}! Please fix."
fi

# Now check the checksum
pushd "$(dirname ${file})"
echo "${checksum}" | sha256sum -c
popd
```

Much easier to read and less complex.

2021-02-06 23:13 UTC, stikonas commented on rootfs.sh
> +	file="$( basename "$url" )"		# e.g. bar.tgz
You don't need outer quotes either. `file=$(basename "$url")` will work.

2021-02-06 23:16 UTC, stikonas commented on rootfs.sh
> +export GITDIR="$PWD"
maybe `basename "$0"` would be better instead of $PWD?

2021-02-07 08:41 UTC, bittorf commented on rootfs.sh
> +checksum_do()
ok,  simplied the thing as much as possible, rebased and add explanations to commit-message.

2021-02-08 05:50 UTC, fosslinux requested changes

2021-02-08 05:50 UTC, fosslinux commented on rootfs.sh
> +	local dir="${CACHEDIR:-$GITDIR/sources/dl}"
`/dl` is still unresolved, do you forsee a particular usecase for sources outside of tarballs?

2021-02-08 05:50 UTC, fosslinux commented on rootfs.sh
> +		mkdir -p "$dir"
Please act on this

2021-02-08 05:50 UTC, fosslinux commented on rootfs.sh
> +checksum_do()
This doesn't even work now, checksum is not calculated. Line 53 is redundant, it does nothing.

2021-02-08 05:51 UTC, fosslinux commented on rootfs.sh
> +checksum_do()
This doesn't even work now, checksum is not calculated. Line 53 is redundant, it does nothing.

2021-02-08 08:55 UTC, fosslinux commented on rootfs.sh
> +export GITDIR="$PWD"
@stikonas we cannot assume that currently, other parts of the script expect to be run from the root of the repository

2021-02-08 08:57 UTC, fosslinux commented on rootfs.sh
> +}
This is a poor style, use an if block instead

```
if [ -f "$GITDIR/rootfs.sh" ]; then
    echo "rootfs must be run from the base of the repo
    exit 1
fi
(false is also incorrect here, exit 1 should be used instead, as that doesn't exploit the use of set -e)

2021-02-08 11:03 UTC, bittorf commented on rootfs.sh
> +		mkdir -p "$dir"
the mkdir? but is is only *needed* in the else-case - or do you mean something different?

2021-02-08 11:09 UTC, bittorf commented on rootfs.sh
> +checksum_do()
it works here and in CI. just try to *change* a checksum in SHA256-file or the remove it. Line 53 is for getting the var "checksum" out of the line (firstword in line).

2021-02-08 11:10 UTC, bittorf commented on rootfs.sh
> +	local dir="${CACHEDIR:-$GITDIR/sources/dl}"
the usecase is in the commit-message:
```
downloads can be made to every location, not
necessary to 'sources', hence to special dir 'dl'.
```

2021-02-08 11:15 UTC, bittorf commented on rootfs.sh
> +}
if fixed it:
we have `set -e`, so when i try to run it from outside, it stop the script:

```
bastian@ryzen:~/software/live-bootstrap-bittorf$ live-bootstrap/rootfs.sh 
+ QEMU_CMD=qemu-system-x86_64
+ QEMU_RAM=8G
++ dirname live-bootstrap/rootfs.sh
+ GITDIR=/home/bastian/software/live-bootstrap-bittorf/live-bootstrap
+ test -f ./rootfs.sh
+ echo 'must be run from base of repo'
must be run from base of repo
+ false
```

2021-02-08 20:26 UTC, fosslinux commented on rootfs.sh
> +		mkdir -p "$dir"
oh, true

2021-02-08 20:30 UTC, fosslinux commented on rootfs.sh
> +checksum_do()
OHH, I get it now. A for loop is quite a bad way to do this, as for is made for looping, and splits on spaces and stuff too. Since a sha256sum file is tab delimited, a much better way to do that construct would be just (replacing lines 52 and 53): `checksum="$(sha256sum <"$dir/$file" | cut -f1)"`, cut takes the first field tab delimited.

2021-02-08 21:23 UTC, stikonas commented on rootfs.sh
> +	grep -q ^"$checksum  $file"$ "$store" || {
It's probably a minor thing but I would feel more comfortable if we rely on sha256sum to check whether hash matches.
I.e. instead of running sha256sum and then use grep to compare, run grep to get sha256sum and run sha256sum --check to verify.

Something like
```
if checksum=$(grep $file SHA256SUMS.sources); then
    (cd $dir; echo $checksum | sha256sum --check )
else
    echo "error"
fi
```
This also has the advantage of printing `tar-1.12.tar.gz: OK` to log.

2021-02-09 05:50 UTC, fosslinux commented on rootfs.sh
> +	grep -q ^"$checksum  $file"$ "$store" || {
Yeah, I agree.

2021-02-10 06:14 UTC, fosslinux requested changes

2021-02-10 06:14 UTC, fosslinux commented on rootfs.sh
> +		echo "# error: add hash to '$store' or remove e.g. partitial downloaded file"
Typo here, but also not an amazing message, a much better message would be "Checksum mismatch or not found!"

2021-02-10 06:14 UTC, fosslinux commented on rootfs.sh
> +}
Please change to if block and use exit 1.

2021-02-10 06:14 UTC, fosslinux commented on rootfs.sh
> +		false
Please use exit 1

2021-02-10 07:40 UTC, fosslinux approved these changes

2021-02-10 07:40 UTC, merged