Add dev nodes to sysc
fosslinux/live-bootstrap pull request #315
Opened 2023-08-01 21:25 UTC by ajherchenroder

This change adds three SATA disks with three partitions each along with three NVME drives with three partitions and a optical drive to sysc.
Fixes Issue# 312

2023-08-03 23:48 UTC, stikonas commented on sysc/after.sh
> +    for a in ${seq 3}; do
Should it be `$(seq 3)`?

2023-08-03 23:51 UTC, stikonas requested changes
Could you please squash it into a singled commit?

2023-08-04 06:26 UTC, ajherchenroder commented
> Could you please squash it into a singled commit?
The last thing I worked on in GitHub squashed the commits automatically. Is there a manual way to do it?

2023-08-05 01:58 UTC, fosslinux commented
You can do an interactive rebase at the terminal (`git rebase -i HEAD~3`, for example to work with the last 3 commits), and then the comment text will explain it.

2023-08-06 14:34 UTC, stikonas approved these changes
I guess looks good. Though I'm a bit confused by indentation here.

@fosslinux what do you think?

2023-08-08 08:31 UTC, fosslinux commented
agreed, I do understand the indenting to indicate sections of code however generally i'd prefer line breaks rather than idents.

2023-08-08 09:16 UTC, ajherchenroder commented
I don’t mind flattening the spacing but but I was attempting to mirror the formatting in run.sh in sysb. Version 0 of this change was just dropping parts of that code in. When I went back and modified it, I kept the formatting to try to keep the look and feel. Let me know what you want me to do.

2023-08-08 09:26 UTC, fosslinux commented
Let's flatten the spacing (but keeping usual indentation for loops, ifs etc).

We follow generally "logic indenting", where each control block indents. That means that when you copy code from one file to another the indentation probably needs to be changed. (Excuse me if you were already aware of this but I think something isn't perfectly clear here.)

2023-08-08 18:10 UTC, nanonyme commented
Just a nit but there's a typo in description which prevents this from actually linking to and closing the related issue.

2023-08-09 22:13 UTC, fosslinux approved these changes
LGTM

2023-08-09 22:22 UTC, stikonas approved these changes

2023-08-09 22:23 UTC, merged