recompile tar and add gzip 1.12 for V1.0 roadmap
fosslinux/live-bootstrap pull request #317
Opened 2023-08-13 00:05 UTC by ajherchenroder

recompile tar and add gzip 1.12 for V1.0 roadmap

Update parts.rst to add tar 1.34 pass 2 and gzip 1.12

Corrected  gzip CRC

2023-08-13 13:43 UTC, stikonas requested changes

2023-08-13 13:43 UTC, stikonas commented on sysc/gzip-1.12/gzip-1.12.sh
> +./configure --prefix=/usr
Indentation, add 4 spaces

2023-08-13 13:43 UTC, stikonas commented on sysc/gzip-1.12/gzip-1.12.sh
> +./configure --prefix=/usr
Do not hardcode `/usr`, we use `--prefix="${PREFIX}"`

2023-08-13 13:43 UTC, stikonas commented on sysc/gzip-1.12/gzip-1.12.sh
> +src_compile() {
remove `src_compile` and `src_install`. Default implementations would work and they are called automatically.

2023-08-13 13:43 UTC, stikonas commented on sysc/run2.sh
> +build tar-1.34
I think you need to add tar build script and also checksum

2023-08-13 13:43 UTC, stikonas commented on parts.rst
> +========
this underline should be of same length as text above, i.e.

```
tar 1.34 (pass 2)
=================
```

2023-08-13 13:43 UTC, stikonas commented on parts.rst
> +==========
same here, line is too long by 1 character.

2023-08-13 13:43 UTC, stikonas commented on sysc/gzip-1.12/gzip-1.12.sh
> +ssrc_prepare() {
`ssrc_prepare` seems to be a typo, it should be `src_prepare`.

2023-08-13 13:43 UTC, stikonas commented on sysc/gzip-1.12/gzip-1.12.sh
> +    default
We want to make sure we regenerate all pre-built non-source file in this stage. At the very least this will need `autoreconf-2.71 -fi`. Most likely there are crc tables that we need to regenerate too (See https://github.com/fosslinux/live-bootstrap/pull/299 for context).

2023-08-13 18:44 UTC, ajherchenroder commented on sysc/gzip-1.12/gzip-1.12.sh
> +    default
Well I’m seeing a pattern here. I do my development on a personal fork that I’ve been modifying to get a gentoo prefix working on. When I do something that may be of interest to the core project, I back port the relevant code into a “clean” version of the core project and remove my comments. Every time I do that my formatting gets messed up. I’m going to have to come up with a better workflow. I’m going to mark this as draft and clean up the formatting. Then I’ll go dig into the technical issues.

2023-08-16 00:17 UTC, stikonas commented
Actually, do we really need to rebuild tar? It's already built using musl toolchain, just using an older gcc compiler.

2023-08-16 00:52 UTC, ajherchenroder commented
It’s on the V1 road map as incomplete. I initially added it as a training tool to start to get a feel for the build system. I don’t really need it for what I’m doing so I could drop it from the PR if you want.

2023-08-16 00:58 UTC, stikonas commented
Apparently, this was an oversight by @fossy. But we should still rebuild gzip.

2023-08-24 00:39 UTC, ajherchenroder commented
I have to travel for work for the next few weeks. I am closing this until I get back and can work on it again.

2023-08-24 00:39 UTC, closed without merging