Comply with REUSE 3.0
fosslinux/live-bootstrap pull request #32
Opened 2021-02-06 23:26 UTC by fosslinux

REUSE is a specification on how repositories should ensure licensing is done properly. Since our licensing is not very simple, I have decided we should use this.

However, I need existing contributors to be clear about the following:

- code changes are licensed under the GNU GPL v3.0 (applicable to @stikonas @bittorf @pder)
- documentation changes are licensed under Creative Commons BY-SA 4.0 (applicable to @stikonas @pder)
- patches are licensed under the license of the project of which they are patching (applicable to @stikonas @pder)

Please ensure that you have been attributed everywhere you should be; if you have time, please also check that I haven't added people (including myself!) where they shouldn't be.

Approving this pull request with a note of something like "I agree to this licensing" should cover any potential issues.

2021-02-06 23:30 UTC, stikonas commented on .gitignore
> +# SPDX-License-Identifier: GPL-3.0-or-later
I would use something simpler for .gitignore... It's just a list of files, so maybe more permissive?

2021-02-06 23:31 UTC, stikonas commented on .gitmodules
> +# SPDX-License-Identifier: GPL-3.0-or-later
If we change .gitignore, maybe this one too...

2021-02-06 23:32 UTC, stikonas commented on rootfs.sh
> +#sudo umount sysa/tmp
intentional?

2021-02-06 23:35 UTC, stikonas commented on sysa/blynn-compiler/blynn-compiler.kaem
> +
This is basically exact copy of `go.sh` from blynn-compiler. We should probably add attributions from there...
Especially for @pder and @oriansj

2021-02-06 23:36 UTC, stikonas commented on sysa/mes/files/mescc.scm
> +; Copyright © 2016,2017,2018,2019 Jan (janneke) Nieuwenhuizen <janneke@gnu.org>
`SPDX-FileCopyrightText` ?

2021-02-06 23:37 UTC, stikonas commented on sysa/mescc-tools-extra/src/chmod.c
> +// Copyright (C) 2020 fosslinux
Remove this line. There is SPDX-FileCopyrightText on the next line

2021-02-06 23:38 UTC, stikonas commented on sysa/mescc-tools-extra/src/cp.c
> +// Copyright (C) 2020 fosslinux
same here

2021-02-06 23:41 UTC, stikonas requested changes
I agree to licensing changes that were described in the comment:

- code changes are licensed under the GNU GPL v3.0
- documentation changes are licensed under Creative Commons BY-SA 4.0
- patches are licensed under the license of the project of which they are patching

2021-02-06 23:41 UTC, stikonas commented on sysa/mescc-tools-extra/src/functions/file_print.c
> +// Copyright (C) 2016 Jeremiah Orians
SPDX-FileCopyrightText

2021-02-06 23:41 UTC, stikonas commented on sysa/mescc-tools-extra/src/functions/in_set.c
> +// Copyright (C) 2016 Jeremiah Orians
SPDX-FileCopyrightText

2021-02-06 23:41 UTC, stikonas commented on sysa/mescc-tools-extra/src/functions/match.c
> +// Copyright (C) 2016 Jeremiah Orians
SPDX-FileCopyrightText

2021-02-06 23:41 UTC, stikonas commented on sysa/mescc-tools-extra/src/functions/numerate_number.c
> +// Copyright (C) 2016 Jeremiah Orians
SPDX-FileCopyrightText

2021-02-06 23:41 UTC, stikonas commented on sysa/mescc-tools-extra/src/functions/require.c
> +// Copyright (C) 2016 Jeremiah Orians
SPDX-FileCopyrightText

2021-02-06 23:41 UTC, stikonas commented on sysa/mescc-tools-extra/src/functions/string.c
> +// Copyright (C) 2016 Jeremiah Orians
SPDX-FileCopyrightText

2021-02-07 06:51 UTC, bittorf commented
I agree to this licensing.

2021-02-08 14:17 UTC, pder commented
I agree to this licensing.

2021-02-08 19:13 UTC, stikonas commented on sysa/tcc-0.9.27/patches/mes-libc-qsort.patch
> -  *
Is this removal intentional?

2021-02-08 20:33 UTC, fosslinux commented on sysa/tcc-0.9.27/patches/mes-libc-qsort.patch
> -  *
Yeah, we don't do this in any other patch and appropriate attribution has been given through the use of SPDX-Copyright header.

2021-02-09 10:24 UTC, merged