Rebuild coreutils-5.0 with tcc+musl and more utilities
fosslinux/live-bootstrap pull request #34
Opened 2021-02-09 14:27 UTC by pder

Add expr, date, dd, sort, uname, uniq

2021-02-09 19:23 UTC, stikonas requested changes

2021-02-09 19:23 UTC, stikonas commented on sysa/coreutils-5.0/mk/pass2.mk
> +PACKAGE=coreutils
```suggestion
# SPDX-FileCopyrightText: 2021 Paul Dersey <pdersey@gmail.com>
# SPDX-FileCopyrightText: 2021 Andrius Štikonas <andrius@stikonas.eu>
#
# SPDX-License-Identifier: GPL-3.0-or-later

PACKAGE=coreutils
```

2021-02-11 05:34 UTC, fosslinux commented on sysa/coreutils-5.0/mk/pass2.mk
> +PACKAGE=coreutils
@pder coudl you please do this

2021-02-11 14:08 UTC, pder commented
Rebased onto master, updated copyright info in pass2.mk, updated numbering in run.sh and README.md and added comm to coreutils build.

2021-02-11 18:30 UTC, stikonas approved these changes

2021-02-11 21:45 UTC, stikonas commented on README.md
> +comm, expr, date, dd, sort, uname, and uniq.
Maybe backtick binaries in README? e.g. comm -> `comm`?

2021-02-11 23:36 UTC, stikonas approved these changes

2021-02-11 23:40 UTC, pder commented on README.md
> +comm, expr, date, dd, sort, uname, and uniq.
Updated the README with backticks

2021-02-12 06:48 UTC, fosslinux commented
Hm, that was not exactly my intention, but that's ok.

2021-02-12 10:47 UTC, merged