Add bison 3.4.1.
fosslinux/live-bootstrap pull request #36
Opened 2021-02-10 18:08 UTC by stikonas

2021-02-10 20:07 UTC, fosslinux requested changes

2021-02-10 20:07 UTC, fosslinux commented on sysa/bison-3.4.1/patches/scan-skel-missing-include.patch
> +# SPDX-FileCopyrightText: 2020 Giovanni Mascellani <gio@debian.org>
The two missing include patches can probably be merged.

Also our patches don't generally have `# ` at the beginning of the SPDX lines (as per all the other patches).

2021-02-10 22:29 UTC, stikonas commented
Minor update: added `yacc` symlink.

2021-02-11 05:35 UTC, fosslinux approved these changes

2021-02-11 05:35 UTC, merged