Fix uninitialized variables in script-generator
fosslinux/live-bootstrap pull request #385
Opened 2024-01-01 21:15 UTC by Googulator

Not sure if the Variable *last one is significant, but the Directive *last can be triggered by having the first directive in the manifest be a define.

2024-01-01 23:20 UTC, stikonas approved these changes

2024-01-01 23:20 UTC, stikonas requested changes
This will need checksum changes?

2024-01-02 00:10 UTC, Googulator commented
> This will need checksum changes.

It appears script-generator isn't currently protected by a checksum. Fixing that should probably be a separate PR, though.

2024-01-02 02:59 UTC, fosslinux approved these changes

2024-01-08 10:47 UTC, merged