Add perl 5.000.
fosslinux/live-bootstrap pull request #40
Opened 2021-02-14 17:49 UTC by stikonas

Adds perl.

`opcode.h` problem is not yet solved but `keywords.h` is now regenerated (defines are off by one but that shouldn't matter).

2021-02-16 20:19 UTC, pder commented on sysa/perl5.000/perl5.000.sh
> +    sed -e '1,/__END__/ d' keywords.pl | sed '1d' | awk '{print "#define", "KEY_"$0, NR-1}' > keywords.h
Could this one-liner be moved into a script named keywords.sh so it is consistent with opcode.sh and embed_h.SH?

2021-02-16 20:40 UTC, pder approved these changes

2021-02-17 05:27 UTC, fosslinux requested changes
Looking pretty good, thank you!

Doesn't miniperlmain need to be "generated" using writemain.SH?

2021-02-17 05:27 UTC, fosslinux commented on sysa/perl5.000/files/keywords.sh
> +# SPDX-License-Identifier: GPL-3.0-or-later
Comment here to the effect of replaces keywords.pl?

2021-02-17 05:27 UTC, fosslinux commented on sysa/perl5.000/files/opcode.sh
> +
Ditto (regarding replaces opcode.pl)

2021-02-17 05:27 UTC, fosslinux commented on sysa/perl5.000/perl5.000.sh
> +    rm perly.c perly.h
Comment remove pregenerated files or something like that

2021-02-17 05:27 UTC, fosslinux commented on sysa/perl5.000/perl5.000.sh
> +    rm embed.h
Comment Regenerate embed.h, etc

2021-02-17 05:27 UTC, fosslinux commented on sysa/perl5.003/perl5.003.sh
> +    rm perly.c perly.h
Comments like from 5.000 please

2021-02-17 06:19 UTC, bittorf commented on rootfs.sh
> +
(and https://github.com/Perl/perl5/archive/perl-5.003.tar.gz)

2021-02-18 07:38 UTC, fosslinux approved these changes

2021-02-18 07:38 UTC, fosslinux commented on README.md
> +### Part 31: perl 5.004_05
Newline (sorry nitpicking :P)

2021-02-18 07:38 UTC, fosslinux commented on README.md
> +### Part 31: perl 5.004_05
I'll merge this now and you can fix this in your next PR :)

2021-02-18 07:38 UTC, merged