Support reboot in non-chroot modes using grub and an init script
fosslinux/live-bootstrap pull request #415
Opened 2024-01-22 16:13 UTC by Googulator

We use grub-2.06 as 2.12 has some packaging issues, and can't be built in live-bootstrap for now.

2024-01-23 09:36 UTC, Googulator commented
This has 2 bugs I've found so far:
- grub.cfg needs to reference $DISK, not $PHYSICAL
- our version of mount (util-linux) still relies on /etc/mtab, rather than /proc/mounts, so after reboot, we don't properly remount auxiliary filesystems - I'm still working on a fix for this

2024-01-24 01:22 UTC, fosslinux requested changes
Just issues with pregened files in grub;

- there is a gnulib in `grub-core/lib/gnulib`
- see `autogen.sh` for a bunch of different regenerations that need to take place (unicode, libgcrypt, autogen-ish)


(Side note; the autogen here is WEIRRRD. Doesn't use proper autogen, rather uses some subset they wrote their own Python parser for a subset of autogen??)

Don't worry about the `contrib/` stuff, that's not really generated code...

2024-01-24 02:17 UTC, Googulator commented
Note also Stikonas's comments in https://github.com/fosslinux/live-bootstrap/pull/418 (they actually belong here)

2024-01-24 02:54 UTC, Googulator commented
> Just issues with pregened files in grub;
> 
>     * there is a gnulib in `grub-core/lib/gnulib`
> 
>     * see `autogen.sh` for a bunch of different regenerations that need to take place (unicode, libgcrypt, autogen-ish)
> 
> 
> (Side note; the autogen here is WEIRRRD. Doesn't use proper autogen, rather uses some subset they wrote their own Python parser for a subset of autogen??)
> 
> Don't worry about the `contrib/` stuff, that's not really generated code...

Should be resolved in the last force-push, but I'm still waiting for the build, to see if the checksum changes.

2024-01-24 21:23 UTC, Googulator commented
Looks like the checksum was unaffected.

2024-01-25 12:40 UTC, Googulator commented
Let's try again with a small fix to ensure reproducibility between 32-bit and 64-bit host kernels (otherwise a 32-bit userspace on a 64-bit kernel would be detected as "i686-pc-linux-muslx32" vs "i686-pc-linux-musl" on a 32-bit kernel).

2024-01-30 22:18 UTC, fosslinux commented on steps/grub-2.06/pass1.sh
> +    CFLAGS="-Wno-error" ./configure --prefix="${PREFIX}" --build=i686-pc-linux-musl
`--sbindir=${PREFIX}/bin`, please, because we aren't using separate `bin` and `sbin` in any other package

2024-01-31 12:40 UTC, Googulator commented on steps/grub-2.06/pass1.sh
> +    CFLAGS="-Wno-error" ./configure --prefix="${PREFIX}" --build=i686-pc-linux-musl
Done, and rebased on current tip.

2024-02-05 07:50 UTC, fosslinux approved these changes

2024-02-05 07:50 UTC, merged