Add gawk 5.3.0
fosslinux/live-bootstrap pull request #429
Opened 2024-01-30 23:55 UTC by fosslinux

2024-02-03 13:30 UTC, stikonas commented on steps/gawk-5.3.0/sources
> +https://ftp.gnu.org/gnu/gawk/gawk-5.3.0.tar.xz ca9c16d3d11d0ff8c69d79dc0b47267e1329a69b39b799895604ed447d3ca90b
let's switch to the same mirror as elsewhere...

2024-02-03 13:30 UTC, stikonas approved these changes

2024-02-04 03:52 UTC, fosslinux commented on steps/gawk-5.3.0/sources
> +https://ftp.gnu.org/gnu/gawk/gawk-5.3.0.tar.xz ca9c16d3d11d0ff8c69d79dc0b47267e1329a69b39b799895604ed447d3ca90b
Oh good point

2024-02-04 12:09 UTC, stikonas requested changes
this is mismerged... There are various merge conflicts.

2024-02-06 07:06 UTC, merged