Install autoconf 2.52.
fosslinux/live-bootstrap pull request #52
Opened 2021-02-26 00:42 UTC by stikonas

Also create device nodes.

2021-02-27 00:35 UTC, fosslinux commented on sysa/autoconf-2.52/autoconf-2.52.sh
> +}
IMO, this belongs in a separate stage. It is not completely related to autoconf and we definitely will use it for other things.

2021-02-27 00:50 UTC, stikonas commented on sysa/autoconf-2.52/autoconf-2.52.sh
> +}
do you think I can put this function to helpers.sh?

2021-02-27 01:04 UTC, fosslinux commented on sysa/autoconf-2.52/autoconf-2.52.sh
> +}
Dislike that, it's not really a helper; I think it would be ok in run.sh though

2021-02-27 01:35 UTC, fosslinux requested changes

2021-02-27 01:35 UTC, fosslinux commented on sysa/autoconf-2.52/autoconf-2.52.sh
> +    install autoconf ${PREFIX}/bin/
Rename the binary to `autoconf252` - this is the standard practice done in most distributions.

2021-02-27 20:10 UTC, stikonas commented on sysa/autoconf-2.52/autoconf-2.52.sh
> +    install autoconf ${PREFIX}/bin/
renamed to autoconf-2.52

2021-02-28 00:30 UTC, fosslinux approved these changes

2021-02-28 01:06 UTC, merged