bash-3.2.57: Build new package to replace bash 2.05b
fosslinux/live-bootstrap pull request #56
Opened 2021-03-04 22:29 UTC by pder

Resulting build now works interactively

2021-03-04 22:46 UTC, stikonas requested changes
Can you also update `README.rst` where we mention that we'll soon have interactive bash.

2021-03-04 22:46 UTC, stikonas commented on parts.rst
> +some included generated files.
Maybe we can make it a bit clearer that interactivity is due to `readline` and not just newer `bash`?

2021-03-04 22:46 UTC, stikonas commented on sysa/run.sh
>  echo "Bootstrapping completed."
Maybe we can add

`exec bash` at the very end after `echo "Bootstrapping completed."`

2021-03-04 23:30 UTC, pder commented on sysa/run.sh
>  echo "Bootstrapping completed."
Instead of exec bash which will never exit, I think we talked about doing exec bash run2.sh which starts the next script under this new interpreter.  Also won't exec bash cause our ci to fail?

2021-03-04 23:57 UTC, stikonas commented on sysa/run.sh
>  echo "Bootstrapping completed."
Well, we definitely can do `exec bash run2.sh` too.

I think CI is scanning for `Bootstrapping completed.` Once it is done CI is killed and marked as successfull.
I think it will still work fine with `exec bash` since current CI doesn't exit anyway, the kernel simply panics and qemu is stuck forever. That's why I was thinking that instead of qemu stuck forever, it would be nicer to show terminal.

But maybe then it's better to do
`exec bash run2.sh`
Move `echo "Bootstrapping completed"` to `run2.sh` and then do `exec bash` after that `echo`.

2021-03-05 11:25 UTC, stikonas commented on parts.rst
> +==========
missing one `=`

2021-03-05 11:26 UTC, stikonas commented on sysa/run2.sh
> +echo "Bootstrapping completed."
please add shebang and spdx stuff.

2021-03-05 21:34 UTC, fosslinux commented on sysa/run2.sh
> +export PREFIX=/after
Is this required? Shouldn't it propagate from the previous script?

2021-03-05 23:16 UTC, fosslinux approved these changes

2021-03-05 23:17 UTC, merged