Diffutils
fosslinux/live-bootstrap pull request #6
Opened 2021-01-11 21:00 UTC by stikonas

2021-01-11 21:37 UTC, fosslinux requested changes
Thank you very much, very good work.

I'm not a fan of the `-boot` on the end of versions, everything in this project is being used for bootstrapping, there's no need to add that IMO.

2021-01-11 21:37 UTC, fosslinux commented on rootfs.sh
> +# sed 4.0.6
4.0.7

2021-01-11 21:37 UTC, fosslinux commented on rootfs.sh
> +url=https://ftp.gnu.org/gnu/tar/tar-1.12.tar.gz
You can use a submodule for this one too then we can get out of submodule land..

Revision `3289dce5520299aeca677b1fc18383961a112949` from https://git.savannah.gnu.org/git/tar.git (luckily they have the entire tree dating back to 1.12!)

2021-01-11 21:37 UTC, fosslinux commented on rootfs.sh
> +cp "../sources/$(basename $url)" tmp/after
Can you make a function to avoid repetition?

2021-01-11 21:37 UTC, fosslinux commented on sysa/diffutils-2.7.kaem
> +# Compile
Move this comment down to line 13

2021-01-11 21:37 UTC, fosslinux commented on sysa/gzip-1.2.4.kaem
> +cp util.c util_patched.c
Is there a particular reason to do this?

2021-01-11 21:37 UTC, fosslinux commented on sysa/sed-4.0.7.kaem
> +tcc -c -I . -I lib -DPACKAGE=\"sed\" -DVERSION=\"4.0.6-boot\" sed/sed.c
`-boot`?

2021-01-11 21:37 UTC, fosslinux commented on sysa/tar-1.12.kaem
> +tcc -c -I lib -DSIZEOF_UNSIGNED_LONG=4 -DHAVE_FCNTL_H -DPACKAGE=\"tar\" -DVERSION=\"1.12-boot\" src/tar.c
`-boot`?

2021-01-11 21:59 UTC, stikonas commented on sysa/gzip-1.2.4.kaem
> +cp util.c util_patched.c
So that patching is idempotent. I don't want second sed run to remove some other lines. For bootstrap purposes this doesn't matter since we only run it once, but for debugging I think it's easier.

2021-01-11 22:00 UTC, stikonas commented on sysa/sed-4.0.7.kaem
> +tcc -c -I . -I lib -DPACKAGE=\"sed\" -DVERSION=\"4.0.6-boot\" sed/sed.c
Replaced with 4.0.7

2021-01-11 22:01 UTC, fosslinux commented on sysa/gzip-1.2.4.kaem
> +cp util.c util_patched.c
Cool

2021-01-12 01:02 UTC, stikonas commented
Should be ready for merge now.

2021-01-12 05:06 UTC, merged