Various fixes
fosslinux/live-bootstrap pull request #67
Opened 2021-03-15 07:18 UTC by fosslinux

Fixing indentation and making aclocal.m4 regenerate for certain.

2021-03-15 20:54 UTC, stikonas requested changes

2021-03-15 20:54 UTC, stikonas commented on sysa/automake-1.4-p6/stage2.sh
>      autoconf-2.52
CI fails here after deletion of `aclocal.m4` but I think swapping `aclocal` and `autoconf` helps.

2021-03-16 00:26 UTC, stikonas commented on sysa/automake-1.4-p6/stage2.sh
>      autoconf-2.52
Feel free to merge once this is fixed.

2021-03-17 20:22 UTC, fosslinux commented
Automake commits superseded by #69.

2021-03-17 20:23 UTC, stikonas approved these changes

2021-03-17 20:29 UTC, merged