GCC
fosslinux/live-bootstrap pull request #75
Opened 2021-03-21 01:13 UTC by stikonas

2021-03-22 06:55 UTC, fosslinux requested changes
Also, `int/` and `gcc/po` should be disabled, as they use things generated by `xgettext`.

2021-03-22 06:55 UTC, fosslinux commented on parts.rst
> +GCC is a key component of the GNU toolchain and the standard compiler for most projects related to GNU and the Linux kernel.
80 char wrap

2021-03-22 06:55 UTC, fosslinux commented on parts.rst
> +Only C frontend is built at this stage.
Only the C frontend....

2021-03-22 06:55 UTC, fosslinux commented on parts.rst
> +This is the latest musl version as of the time of writing.
Maybe note that we can now drop `tcc` patches and that is what allows for the latest version?

2021-03-22 06:55 UTC, fosslinux commented on sysa/bash-5.1/bash-5.1.sh
>          ./configure --prefix="${PREFIX}" \
Reduce indentation here now?

2021-03-22 06:55 UTC, fosslinux commented on sysa/bash-5.1/bash-5.1.sh
> +    install bash "${PREFIX}/bin"
??

2021-03-22 06:55 UTC, fosslinux commented on sysa/gcc-4.0.4/pass1.sh
> +    for dir in fixincludes gcc intl libcpp libiberty; do
All these dirs also need aclocal AFAICT:

```
➜ find . -name aclocal.m4
./fixincludes/aclocal.m4
./libcpp/aclocal.m4
./libmudflap/aclocal.m4
./libiberty/aclocal.m4
./intl/aclocal.m4
./gcc/aclocal.m4
```

2021-03-22 06:55 UTC, fosslinux commented on sysa/gcc-4.0.4/pass1.sh
> +      --disable-libmudflap
4 space indentation?

2021-03-22 06:55 UTC, fosslinux commented on sysa/gcc-4.0.4/pass2.sh
> +# SPDX-FileCopyrightText: 2021 Andrius Štikonas <andrius@stikonas.eu>
Please apply any changes made in pass1 here also.

2021-03-22 06:55 UTC, fosslinux commented on sysa/musl-1.2.2/musl-1.2.2.sh
> +      --includedir=/after/include/
4 space indenting

2021-03-22 18:12 UTC, stikonas commented on sysa/bash-5.1/bash-5.1.sh
> +    install bash "${PREFIX}/bin"
`${bindir}` is not defined in bash-5.1.sh. I think it was working because it propagated from some other file (tcc?). And for now we don't have subshells (they didn't work well with bash-mes).

2021-03-22 18:21 UTC, stikonas commented on parts.rst
> +This is the latest musl version as of the time of writing.
latest version is allowed by GCC, unrelated to patches.

2021-03-22 18:23 UTC, stikonas commented on sysa/gcc-4.0.4/pass1.sh
> +    for dir in fixincludes gcc intl libcpp libiberty; do
libmudflap is already rebuilt by `autoreconf`. I'll check the others.

2021-03-22 23:26 UTC, stikonas commented on sysa/gcc-4.0.4/pass1.sh
> +    for dir in fixincludes gcc intl libcpp libiberty; do
Only `./intl/aclocal.m4` and `./libcpp/aclocal.m4` seem to be generated by aclocal.

The other files seem to be maintained by hand. In later versions of GCC they were moved into `acinclude.m4` that is used by aclocal and included as part of generated aclocal.m4.

2021-03-24 08:51 UTC, fosslinux requested changes

2021-03-24 08:51 UTC, fosslinux commented on sysa/bash-5.1/bash-5.1.sh
> +    --enable-static-link
Indent by four spaces these lines.

2021-03-25 07:46 UTC, fosslinux approved these changes

2021-03-25 07:46 UTC, merged