Port rootfs.sh to Python
fosslinux/live-bootstrap pull request #91
Opened 2021-04-07 22:21 UTC by stikonas

Old rootfs.sh is not yet removed in this PR.

2021-04-08 08:17 UTC, fosslinux requested changes
Reasonably good.

I think that I prefer sysa as a class more. It seems pretty clear usecase for OOP and the globals seem really hacky. I think it is easier to reason about with a class, but up to you.

There should be many more comments. This needs to be easily reproducible by someone without using this script, arguably the most important part of live-bootstrap that needs to be manually doable. If the function descriptions, particularly around get_file and the like, and the comments scattered around there, are replicated in other functions, that would be great.

2021-04-08 08:17 UTC, fosslinux commented on rootfs.py
> +
Again double newline.

Also you probably want some kind of option validation here that ensures only one of chroot/qemu/minikernel is selected, otherwise there is a whole host of issues.

2021-04-08 08:17 UTC, fosslinux commented on rootfs.py
> +                                    stdout=subprocess.PIPE)
Not sure how much I like shelling out to find... it shouldn't be too hard to do this in native Python?

2021-04-08 08:17 UTC, fosslinux commented on rootfs.py
> +        run('git', 'clone', 'depth', '1', '--branch', 'v0.4', 'https://github.com/bittorf/kritis-linux.git')
`--depth`

2021-04-08 08:17 UTC, fosslinux commented on rootfs.py
> +            '-m', str(args.qemu_ram) + 'G', '--kernel', '5.10.8', '--initrd', initramfs_path)
Parser description says "Memory (in megabytes) allocated to QEMU VM".. but you have G here.

2021-04-08 08:17 UTC, fosslinux commented on rootfs.py
> +    init = os.path.join(os.sep, 'bootstrap-seeds', 'POSIX', args.arch, 'kaem-optional-seed')
We only need to eval this for chroot.

2021-04-08 08:17 UTC, fosslinux commented on rootfs.py
> +                        default="x86")
This needs to have a catch or some other kind of check around it that ensures it only accepts i386/x86, we don't want people getting the idea they can use other architectures.

2021-04-08 08:17 UTC, fosslinux commented on sysa.py
> +    global _arch, _preserve_tmp, tmp_dir, sysa_dir, after_dir
Python globals persist outside files, no? That would be a problem for sysb and higher.

2021-04-08 08:17 UTC, fosslinux commented on sysa.py
> +    abs_file_name = os.path.join(cache_dir, file_name)
Do we need a separate variable here?

2021-04-08 08:17 UTC, fosslinux commented on sysa.py
> +    for i,_ in enumerate(urls):
`i, _` preferably

2021-04-08 08:17 UTC, fosslinux commented on sysa.py
> +    for i,_ in enumerate(urls):
`i, _` preferably

2021-04-08 08:17 UTC, fosslinux commented on rootfs.py
> +    parser.add_argument("-m", "--minikernel", help="Build minikernel",
Use minikernel maybe? Build minikernel kinda implies it's just being buildt and not used, or build inside live-bootstrap.

2021-04-08 08:17 UTC, fosslinux commented on rootfs.py
> +                        action="store_true")
This is probably clearer with a default.

2021-04-08 08:17 UTC, fosslinux commented on rootfs.py
> +    parser.add_argument("-t", "--tmpdir", help="SysA temporary directory")
Can we make the description Temporary directory or otherwise distinguish the argument for sysb etc?

2021-04-10 00:14 UTC, stikonas commented on rootfs.py
> +    parser.add_argument("-t", "--tmpdir", help="SysA temporary directory")
I've now replaced it with `Temporay directory`. I don't think we'll need a separte temp dir for sysb as we have to create it inside sysa.

2021-04-10 00:16 UTC, stikonas commented on rootfs.py
> +                        action="store_true")
Can you clarify this? store_true automatically has default value of `False`. If `-p` is specified than `args.preserve=True`.

2021-04-10 01:07 UTC, stikonas commented
CI failed due to my python being newer. I guess need to fix code a bit to work with older python...

2021-04-10 10:30 UTC, stikonas commented on sysa.py
> +    abs_file_name = os.path.join(cache_dir, file_name)
Hmm, I think I used a separate variable not to accidentally modify file_name that is passed from outside into the function.

2021-04-10 22:57 UTC, fosslinux requested changes
The python script looks great. Can we perhaps shorten or remove `.pylintrc`? It's very long and I'm not sure if its really necessary to check the entire thing into the repo.

2021-04-11 10:08 UTC, merged